### ISSUE TITLE
Support /public/ directory

### ISSUE THREAD

**Issue by millette** [shadowwalker/next-pwa#1]
For reference: <https://github.com/zeit/next.js/issues/7800#issuecomment-509436616>

Both `sw.js` and `precache-manifest.*.js` should go in the root directory. Next 9 adds support for root files (robots.txt, favicon.ico, etc.) with a `/public/` directory (that will eventually replace /static/ too).

For now, a user wishing to use the /public/ directory feature must enabled by adding this snippet in `next.config.js`:

```js
{
  experimental: { publicDirectory: true },
}
```

Not sure if the location of `manifest.json` is harcoded into /static/ but we might want ot look in /public/ too.

**Comment by shadowwalker** [comment]
@millette Just know next.js 9 is out! That's great, I will play around with it and update the feature accordingly.

**Comment by shadowwalker** [comment]
@millette Hi, check out this [example](https://github.com/shadowwalker/next-pwa/tree/master/examples/next-9), it uses `public` folder to serve service worker files in root path instead using a custom server.

**Comment by millette** [comment]
Thanks for the example. I think it could be simplified if /static is renamed to /public and the paths refering to /static/ could be rewritten (/static/manifest.json becomes /manifest.json.) Or if we prefer to keep the /static prefix, simply move /static into /public directory since /public is probably going to replace /static in nextjs eventually.

It's a bit late here, I'll try to come up with a small example to explain better.

**Comment by shadowwalker** [comment]
I already tried what you said, looks like it only serve what in public folder directly, public/static does not work. Looks like public folder is meant to put robot.txt, service worker or maybe manifest.json at this point, other assets goes to static. It's totally fine.

**Comment by millette** [comment]
@shadowwalker I was basing my comment on <https://github.com/zeit/next.js/issues/7800#issuecomment-509436616>
