### ISSUE TITLE
service workers not register on real device

### ISSUE THREAD

**Issue by benamm** [shadowwalker/next-pwa#100]
What can I help with? Please keep this clear and concise.
i try to open app in mobile browser and disconnect device internet and server..
but i cant see service workers caches files in browser.

<img width="1019" alt="Screen Shot 1399-06-26 at 19 33 11" src="https://user-images.githubusercontent.com/40948849/93355600-7fe66100-f853-11ea-9e28-7623a3059eee.png">

**Comment by paales** [comment]
Only works over https and real domains?

**Comment by shadowwalker** [comment]
@paales is right, it's a security requirement that the web app and the service worker must be served over https or http on `127.0.0.1` i.e. `localhost`. You are accessing the web app on LAN using IP address, so it won't install the service worker.

**Comment by benamm** [comment]
thank you @paales @shadowwalker.
