### ISSUE TITLE
how optimize media

### ISSUE THREAD

**Issue by benamm** [shadowwalker/next-pwa#101]
before cache media 
app size look like that 

<img width="622" alt="Screen Shot 1399-06-27 at 11 45 17" src="https://user-images.githubusercontent.com/40948849/93432862-596c0880-f8db-11ea-8d43-fba26ac4f566.png">

but after cache media (4 image) with 19KB size, application size look like that

<img width="622" alt="Screen Shot 1399-06-27 at 11 49 31" src="https://user-images.githubusercontent.com/40948849/93433327-e616c680-f8db-11ea-92f9-8c7fb1b7b013.png">

how optimize cache size?

**Comment by shadowwalker** [comment]
Tune the `runtimeCaching` config as needed to limit the scope of the caches.
