### ISSUE TITLE
Duplicated log "PWA support is disabled"

### ISSUE THREAD

**Issue by tkrotoff** [shadowwalker/next-pwa#105]
With:

```JavaScript
withPWA({
  pwa: {
    disable: process.env.NODE_ENV === 'development'
  }
})
```

You get a double log:

```
$ npm run dev

...

ready - started server on http://localhost:3000
> [PWA] PWA support is disabled
> [PWA] PWA support is disabled

...
```

**Comment by JohnRoseDev** [comment]
Just fyi, still seeing this in next 12.2.5 and next-pwa 5.6.0 when setting `disable: process.env.NODE_ENV === 'development'`:

> [PWA] PWA support is disabled
> [PWA] PWA support is disabled

**Comment by tomasconnor** [comment]
+1

**Comment by Hilver** [comment]
+1

**Comment by DieterNonneman** [comment]
+1

**Comment by ucefkh** [comment]
+3

**Comment by mohammadzeyghami** [comment]
+1

**Comment by Jecta** [comment]
+1

**Comment by wendellpbarreto** [comment]
+1

**Comment by EdouardCRT** [comment]
+1

**Comment by pkalani1999** [comment]
> With:
> 
> ```js
> withPWA({
>   pwa: {
>     disable: process.env.NODE_ENV === 'development'
>   }
> })
> ```
> 
> You get a double log:
> 
> ```
> $ npm run dev
> 
> ...
> 
> ready - started server on http://localhost:3000
> > [PWA] PWA support is disabled
> > [PWA] PWA support is disabled
> 
> ...
> ```

- check your manifest.json.
- check src image is missing form public folder.
