### ISSUE TITLE
start_url does not respond with a 200 when offline

### ISSUE THREAD

**Issue by Spijkervet** [shadowwalker/next-pwa#107]
# Summary
After running the `./examples/next-9` example, the following error appears in Lightbox using Chrome on macOS:
```
start_url does not respond with a 200 when offline
The start_url did respond, but not via a service worker.
A service worker enables your web app to be reliable in unpredictable network conditions.
```

# How To Reproduce
1. Go to ./examples/next-9
2. Run all commands

Link to minimal reproduce setup repository if any.

# Expected Behaviors
A fully working PWA

# Screenshots
https://pasteboard.co/Jw5UFf4.png

**Comment by shadowwalker** [comment]
The issue could be reproduced, but it seems to be an issue with lighthouse.
The URL is indeed responded through service worker.
![image](https://user-images.githubusercontent.com/9603375/96535075-e8a36d80-1245-11eb-8563-f928246a6202.png)

**Comment by Spijkervet** [comment]
Yes, I assumed that was the case. It seems to pass all other tests :)

**Comment by richardthombs** [comment]
@shadowwalker  You really need to put this on the README or rename one of the issues so that it has the exact error message, because I couldn't find this very easily when searching after it happened to me.
