### ISSUE TITLE
The start_url did respond, but not via a service worker.

### ISSUE THREAD

**Issue by ancoiscailletfr** [shadowwalker/next-pwa#108]
When I ran Lighthouse audit on my app (locally or remote) i got error on : start_url does not respond with a 200 when offline, The start_url did respond, but not via a service worker. 
that was seemed to work fews days before..

`
"start_url": "/",
`

Versions: 
- "next": "9.5.5"

thank you for you help 😊

# How To Reproduce
- run lighthouse

# Screenshot
![image](https://user-images.githubusercontent.com/72032505/97086905-7a382400-1626-11eb-81e5-1f78656e2b92.png)

# conf 

```
const withPWA = require('next-pwa')
const runtimeCaching = require('next-pwa/cache')

module.exports =
      withPWA({
        pwa: {
          dest: 'public',
          runtimeCaching
        }
      })
```

**Comment by shadowwalker** [comment]
Duplicate https://github.com/shadowwalker/next-pwa/issues/107
