### ISSUE TITLE
[Feature Request] Generate sw.js with no logging or assertions for the production environment

### ISSUE THREAD

**Issue by toshi1127** [shadowwalker/next-pwa#109]
# Summary

Can you add functionality to sw.js to generate sw.js for the production environment with no logs or assertions?

From what I've read in [official workbox documentation](https://developers.google.com/web/tools/workbox/guides/configure-workbox#configure_debug_builds_vs_production_builds), adding `workbox.setConfig({ debug: true });` will switch to the build for the production environment.

![image](https://user-images.githubusercontent.com/32378535/97110305-d7fa6800-171b-11eb-85a4-b47334b7aacf.png)

```
For each of the Workbox libraries, there are two builds: one for development and one for production.
Debug Builds: Come un-minified, have additional logging and performs rigorous assertion checking to make development as easy as possible.
Production Builds: Are minified with any optional logging and assertions stripped from the build.
```

**Comment by shadowwalker** [comment]
@toshi1127 Hi, actually you already have the power to do that. I added couple tips for your use cases.
Checkout point 6 and 7 in tips: https://github.com/shadowwalker/next-pwa/blob/master/README.md#tips

**Comment by toshi1127** [comment]
@shadowwalker 
Thank you! It's confirmed.
