### ISSUE TITLE
is behind redirect

### ISSUE THREAD

**Issue by nadjarben** [shadowwalker/next-pwa#11]
Hi everybody

When I use next-pwa i get this errors :

The script resource is behind a redirect, which is disallowed.

Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://digiscards.com/') with script ('https://digiscards.com/sw.js'): The script resource is behind a redirect, which is disallowed.

Any clue of how to fix it ?

**Comment by shadowwalker** [comment]
@nadjarben I will take a look.

**Comment by shadowwalker** [comment]
@nadjarben Hi, how was the `sw.js` being hosted. If it's behind a redirect, due to security reason, the browser won't allow the service work to run in the background. It must be directly hosted on your server.

**Comment by nadjarben** [comment]
It used to work in all all my projects, the only difference in this one is that I use i8next translation do you think it could be the reason. It redirect the url to /en /fr ... ?

**Comment by shadowwalker** [comment]
Yes, it could be the cause. You need to figure out a way to host it directly from root path, maybe override the route

**Comment by bcjohnblue** [comment]
I used i18next translation and face the same problem too. Can anyone provide a tutorial solution ?

**Comment by shadowwalker** [comment]
@bcjohnblue I can see if I could build a quick example for you.

**Comment by shadowwalker** [comment]
@nadjarben @bcjohnblue Hi all, I finally got a working example, please checkout the `next-i18next` example.
The key lines are here:
https://github.com/shadowwalker/next-pwa/blob/164a8c4827f033d28b4d608ed0dc5595196c8540/examples/next-i18next/index.js#L32-L36

**Comment by bcjohnblue** [comment]
@shadowwalker Thanks for your example, it can work correctly. By the way, I found setting `ignoreRoutes: ['/sw.js', '/workbox-']` of the `next-i18next` configs can work too.
