### ISSUE TITLE
[Question] Should I add to .gitignore?

### ISSUE THREAD

**Issue by votemike** [shadowwalker/next-pwa#110]
# Summary
There is nothing in the README about adding anything to the gitignore.
But I feel that sw.js, sw.js.map, workbox-{hash}.js and workbox-{hash}.js.map should be gitignored as locally they are not built with production in mind. It feels like something that should be dealt with in the build pipeline, not in GIT.
Before I go ahead with this, I just wanted to check. And I thought it might be a good idea to update the README if I'm correct.

Should I add public/sw.js* and public/workbox-*.js* to my gitignore?

**Comment by shadowwalker** [comment]
This information is in the README.md file in every examples, checkout one here:
https://github.com/shadowwalker/next-pwa/tree/master/examples/custom-worker

**Comment by votemike** [comment]
Ahh, I didn't see the examples.
I was only looking in the main README: https://github.com/shadowwalker/next-pwa

Thanks

**Comment by DSIW** [comment]
I agree, an explicit section would be helpful

**Comment by rcb4t2** [comment]
+1 to add info about .gitignore to the main README
