### ISSUE TITLE
Does not work correctly with webpack 5

### ISSUE THREAD

**Issue by yhay81** [shadowwalker/next-pwa#111]
# Summary

I cound not build correct pwa with next.js 9.5 new feature, webpack 5 support(beta).
Because this is beta feature, it might be fixed automatically by next.js.
Just for reporting.

# How To Reproduce

1. Clone https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app
2. Add webpack 5 resolutions to packege.json like below
(ref. https://nextjs.org/blog/next-9-5#webpack-5-support-beta)

```package.json
{
"resolutions": {
    "webpack": "^5.3.2"
  }
}
```

3. `yarn install  && yarn build && yarn start`

# Additional Context

I am not sure but sw.js seems to try to access the URL like below but cannot.
`/autostatic/*`

--

**Comment by SemperFortis** [comment]
I'm having the same issue, it keeps prefixing it with `/autostatic/`. This was not happening couple weeks ago.

**Comment by dugagjin** [comment]
Same issue, it tries to fetch:

![image](https://user-images.githubusercontent.com/16219574/99274423-9b0d2700-282a-11eb-9b73-e07418ad4d52.png)

from `/autostatic/*`

**Comment by shadowwalker** [comment]
Try `yarn add next-pwa@beta`, see if that works for you.

**Comment by yhay81** [comment]
`yarn add next-pwa@beta` works for me 💯

**Comment by SemperFortis** [comment]
Works for me too
