### ISSUE TITLE
Multi languages

### ISSUE THREAD

**Issue by mohux** [shadowwalker/next-pwa#112]
Hello,

I'm using a multi-language solution with next-pwa 

which redirects the user from "/" to "/[lang]" via 302 redirects

when running audit
it treats it as non 200 urls

and am not able to find a way to register multiple "start_urls", (one for each language)

Is it possible to solve?

**Comment by shadowwalker** [comment]
You should not register multiple "start_urls" for each language.
What do you mean about this?
> it treats it as non 200 urls

**Comment by mohux** [comment]
@shadowwalker thanks for you replaying

since the start_url is "/"

but this page is redirect the user to another page with "302" status code to a URL with language "/en" for example

so audit is show this
![image](https://user-images.githubusercontent.com/57658626/97985918-fb8f7380-1de9-11eb-9a30-e3d4f322981d.png)

**Comment by JerryGreen** [comment]
I think you should dynamically create `manifest.json` files on building step (`yarn build`), each with some little tweaks like different name, description, and start_url.

I'm looking forward making something like this too, but won't need this particular thing for quite a long time probably, - have many other things to do

**Comment by pqminh** [comment]
I got same issues with multi languages support using redirects.
Please help me!
`
async redirects() {
    return [
      {
        source: "/catchAll",
        destination: "/en",
        locale: false,
        permanent: false,
      },
      {
        source: "/catchAll/:slug*",
        destination: "/en/:slug*",
        locale: false,
        permanent: false,
      },
      {
        source: "/404",
        destination: "/en/404",
        locale: false,
        permanent: false,
      },
      {
        source: "/500",
        destination: "/en/500",
        locale: false,
        permanent: false,
      },
    ];
`
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/sw.js'): The script resource is behind a redirect, which is disallowed.

"next": "^10.0.8",
"next-pwa": "^5.1.4",
