### ISSUE TITLE
Exlude urls from being processed by workbox

### ISSUE THREAD

**Issue by pecoram** [shadowwalker/next-pwa#113]
Hi,
is there a way to exclude some url (specially third parties analytics tracking like parsely or comscore) from being processed by workbox?
I have already tried to use the NetworkOnly strategy for these urls but passing through the service walker the tracking is called twice (the second one with a different type) and this distorts the data.

![image](https://user-images.githubusercontent.com/33352553/97860726-ec81c600-1d02-11eb-9d2c-441da9b495c4.png)

Do you have any ideas?

thanks!

**Comment by shadowwalker** [comment]
The request is not called twice. instead, it's one request with 2 stops:
```
window issued request -> service worker intercept the request and because "NetworkOnly" strategy -> fetch from network
```
What do you mean it distorts the data?

**Comment by pecoram** [comment]
It seems (I don't know why) on the analytics dashboard that tracking are counted two times.
Could it be the type change of the response (from gif to fetch)?
I would try to bypass the service worker for that url. Is there a way?

**Comment by shadowwalker** [comment]
If you have `runtimeCaching` configured based on the default caching, modify the part below.
https://github.com/shadowwalker/next-pwa/blob/59dc9ed384873f46d3705387103eda04c6ea19d6/cache.js#L43-L53

### To This

``` javascript
 { 
   urlPattern: /\.(?:jpg|jpeg|png|svg|ico|webp)$/i,                 // remove gif from here
   handler: 'StaleWhileRevalidate', 
   options: { 
     cacheName: 'static-image-assets', 
     expiration: { 
       maxEntries: 64, 
       maxAgeSeconds: 24 * 60 * 60 // 24 hours 
     } 
   } 
 },
 { 
   // negative Lookahead trick, this will skip /ignore1.gif, /ignore2.gif while still do the "StaleWhileRevalidate" for other gif files
   urlPattern: /^(?!ignore1|ignore2)(.*)\.gif$/i,
   handler: 'StaleWhileRevalidate', 
   options: { 
     cacheName: 'static-image-assets', 
     expiration: { 
       maxEntries: 64, 
       maxAgeSeconds: 24 * 60 * 60 // 24 hours 
     } 
   } 
 },
```

The `(?!xxx)` is called negative lookahead in regex, you can use it to do the excluding trick.

**Comment by pecoram** [comment]
Thanks @shadowwalker. It works!
I just had to delete the final _$_ because putting it didn't work with external urls.
