### ISSUE TITLE
Lighthouse Report shows start_url does not respond with a  200 when offline.

### ISSUE THREAD

**Issue by NJITman** [shadowwalker/next-pwa#114]
I am using next-pwa@3.1.5 with next@10.0.0 using the following configuration:

`next.config.js
`
```javascript
const withPWA = require('next-pwa')

module.exports = withPWA({
  pwa: {
    dest: 'public'
  }
})
```

`manifest.json
`
```JSON
{
  "name": "name",
  "short_name": "name",
  "lang": "en-US",
  "start_url": "/",
  "display": "standalone",
  "theme_color": "#000000",
  "background_color": "#ffffff",
  "icons": [
    {
      "src": "/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "/icons/icon_192x192_maskable.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "any maskable"
    }
  ]
}
```

Everything works as expected in production - service worker is registered, pages are delivered from service worker and on the Lighthouse Report I get 90+/100/100/100 marks.  On the PWA report, I consistently get dinged for the following issue (see attached screenshot).

**start_url does not respond with a 200 when offline.  The start_url did respond, but not via a service worker.**

The link in the report takes you to the following site:
[https://web.dev/offline-start-url/?utm_source=lighthouse&utm_medium=devtools](url)

I can run the app in offline mode on desktop and mobile devices, so I know the service worker is running.  Not sure if this is just a bug in the lighthouse report or if I am missing something in the config.

![image](https://user-images.githubusercontent.com/10375636/98583527-88c34400-2292-11eb-9bbd-0922210e02f3.png)

**Comment by mohux** [comment]
Same happening to me

**Comment by shadowwalker** [comment]
It's a know issue for light house, duplicated here:
https://github.com/shadowwalker/next-pwa/issues/107
