### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by mohux** [shadowwalker/next-pwa#115]
I am using the offline page example https://github.com/shadowwalker/next-pwa/tree/master/examples/offline-fallback

But some of the pages got POST requests which leads to ```TypeError: Request method 'POST' is unsupported```

How may I tell the workbox to ignore any POST request from being cached?

**Comment by shadowwalker** [comment]
That's right, POST won't work due to limitation of service worker. You should remove these lines:
https://github.com/shadowwalker/next-pwa/blob/59dc9ed384873f46d3705387103eda04c6ea19d6/examples/offline-fallback/service-worker.js#L89-L97

I will fix this in example when I have time.

**Comment by mohux** [comment]
Actually these lines werent the issue only

When I ran the development mode

It told me that a staleWithoutRevalidate was calling the POST

which was the default header after some debugging

Since the APIs were called in client side

I removed the default headers, rebuilt and unregistered the service workers

And it worked

I had to remove the post you mentioned as well

**Comment by mohux** [comment]
Is there a way to tell the default header to ignore anything that isnt get??

**Comment by shadowwalker** [comment]
Currently, there is no way to do that.
I'm waiting for the new workbox release, we may get some good features there.

**Comment by mohux** [comment]
The weird part is defaultHeaders, shouldn't default header by default only look for gets? that means that default headers should be only used in project/pages where no post requests are happening?

**Comment by shadowwalker** [comment]
@mohux Can you create a minimal reproduce repo for diagnose the issue?
