### ISSUE TITLE
instructions unclear for first time next.js users

### ISSUE THREAD

**Issue by kylebakerio** [shadowwalker/next-pwa#118]
# Summary

the readme assumes user has next.js installed.

# How To Reproduce

following the how-to on the readme leads to a problem when 'next' insn't installed. Tried install next, got problems with react not being installed. Tried installing it globally. Then noticed the react error. Tried installing react and react dom. Still wouldn't work, think I ran into [this problem](https://github.com/vercel/next.js/issues/1588). Just, a chain of annoying problems all caused by an unclear instructional that made an assumption.

Could just add a package.json with next and react and react-dom that is pulled when installing this repo and not even need to update the readme.

**Comment by kylebakerio** [comment]
Beyond this / having 'solved' (?) the above issue, the guide is also generally unclear. At this point, there are just too many assumptions made here about what the reader knows, I guess. Maybe this is intentional and this repo is only targeted at experienced next.js users who have done this process themselves before and just need a boilerplate. For now, I'll just instead go create a vanilla next.js project from scratch and turn it into a PWA myself.

**Comment by kylebakerio** [comment]
ironically, found that this repo is utilized by next.js's pwa example, but that their single command was a lot more straightforward:

`npx create-next-app --example progressive-web-app progressive-web-app`

this is more what I hoped for from this repo's readme, I guess? anyways, just sharing a user experience. You may choose to update the readme or not based on your intentions.

**Comment by shadowwalker** [comment]
Update lines in README.md file for fresh beginners.
