### ISSUE TITLE
disable sw.js generation

### ISSUE THREAD

**Issue by vinkovsky** [shadowwalker/next-pwa#119]
Hi! Could you please explain to me if it is possible to disable sw.js generation in development mode? Solutuion to add `disable: process.env.NODE_ENV! == 'production' in next config doesn't seem to fix it

**Comment by JerryGreen** [comment]
You seem to use it incorrectly, because I've just used this with next-9 example and it works perfectly:

https://github.com/shadowwalker/next-pwa/tree/master/examples/next-9

98% chance you messed up with `next.config.js`

**Comment by JerryGreen** [comment]
Oh wait, process.env.NODE_ENV! == **'production'** ???
That's where the mistake. Development mode is called "development" ;)

**Comment by JerryGreen** [comment]
`process.env.NODE_ENV! == 'production'` looks kinda weird btw
You probably wanted `process.env.NODE_ENV !== 'production'`

**Comment by vinkovsky** [comment]
Im sorry, i so stuipid, i just copied it from my another question from closed issue. My config looks like this 
`const withPWA = require("next-pwa");
const runtimeCaching = require("next-pwa/cache");
runtimeCaching[0].handler = "StaleWhileRevalidate";

module.exports = withPWA({
  pwa: {
    dest: "public",
    register: false,
    disable: process.env.NODE_ENV === "development",
    skipWaiting: false,
    runtimeCaching,
  },
})`

My app based on this [example](https://github.com/shadowwalker/next-pwa/tree/master/examples/lifecycle)

**Comment by shadowwalker** [comment]
Did you actually set `process.env.NODE_ENV` to `development` when you run your app in dev mode? That document is an example, the way you get a true value in dev mode is up to you.
The code logic is correct, you can try it out when arbitrarily set it to true.

**Comment by vinkovsky** [comment]
Hello! Here are my scripts

  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "NODE_ENV=production node server.js",
  }

I think the nextjs starts automatically in development mode

**Comment by shadowwalker** [comment]
Then you need to set your configuration like this:

``` javascript
disable: process.env.NODE_ENV !== "production"
```

**Comment by JerryGreen** [comment]
@vinkovsky why your "start" command is "node"? Why not default "next start"? That's not very nextjs-y to have a custom node server, and `next-pwa` doesn't require it either

**Comment by vinkovsky** [comment]
Thanks for answer @JerryGreen !  This is because I need some logic, for example I am using a sitemap generator and it needs a custom server.  I only run this command in production mode

**Comment by shadowwalker** [comment]
@vinkovsky that is OK, at least you know how to work out your use case
