### ISSUE TITLE
Any plans toward typescript support?

### ISSUE THREAD

**Issue by JerryGreen** [shadowwalker/next-pwa#121]
I see it's not supported:

https://github.com/shadowwalker/next-pwa/blob/515c18d7638d59267ccc719c558593d73a20b6a7/examples/custom-worker/README.md#L15

It would be cool to be able to write custom service worker in `worker/index.ts` out of the box. Also, there's `window` object that has `workbox`, and it also would be cool if it had built-in types... TypeScript is kinda first-class citizen in NextJS after all

**Comment by jsmon** [comment]
I've created a draft PR in DefinitelyTyped/DefinitelyTyped#52042 to add types, but I'm not sure if I've correctly typed the parameters and return type, so could someone please review it. If I've typed it correctly I'll be able to merge it in. Thanks!

**Comment by jsmon** [comment]
I just realised that this issue is about not being able to run `worker.ts` files, not about TypeScript typings, sorry!
