### ISSUE TITLE
Add blacklist to PWA

### ISSUE THREAD

**Issue by jhenriquevissotto** [shadowwalker/next-pwa#122]
I have too much problens with video play.

I have videos hosted in AWS S3 and a server express that redirect that url in src attr of video tag to correct video file in S3.

Often I have this problem:
https://stackoverflow.com/questions/47676422/video-seeking-does-not-work-in-pwa-progressive-web-app

The crossOrigin="true" in attr video tag solve some cases, but others not.

What I want say?

That the PWA could have a config option for exclude the cache of file that contains some strings.

Example:

```javascript
module.exports = withPWA({
    pwa: {
        dest: 'public',
        runtimeCaching: runtimeCaching,
        notCache: ['/stream-video-path']
    }
})
```

**Comment by JerryGreen** [comment]
There's `publicExcludes` and `buildExcludes`, - isn't that enough for you?

**Comment by jhenriquevissotto** [comment]
Sorry.

Reading now my issue sounds a bit rude.

I don't think so.

I guess that both options excludes only files from next server. My videos are hosted in another domain.

**Comment by shadowwalker** [comment]
You can customize runtime cache to fulfill what you need.

**Comment by zsoro2** [comment]
I try to exclude /admin and /api from the cache. I tried to implement this solution below. But I got an error. Any example of how should I exclude these urls for the service worker? 

```
module.exports = withPWA({
  pwa: {
    dest: 'public',
    runtimeCaching: [
      {
        urlPattern: /\/api\/.*$/i,
        handler: 'NetworkOnly'
      }
    ]
  }
});
```

`TypeError: Cannot read property 'cacheName' of undefined`

**Comment by shadowwalker** [comment]
@zsoro2 Please refer to https://github.com/shadowwalker/next-pwa/blob/master/cache.js when writing your own custom runtimeCaching rules.
