### ISSUE TITLE
bad-precaching-response for public directory

### ISSUE THREAD

**Issue by dhmacs** [shadowwalker/next-pwa#123]
# Summary

next-pwa tries to cache assets under `/public` directory using wrong path (e.g. it tries to cache http://localhost:3000/public/nx-logo-white.svg instead of http://localhost:3000/nx-logo-white.svg resulting in a `bad-precaching-response` because it does not find the file).

I feel like I'm doing something wrong since this is a simple scenario, if you can point me out to where the issue might be it would be awesome 🙏 

# How To Reproduce

**next.config.js**
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const withPWA = require("next-pwa");
const withNx = require("@nrwl/next/plugins/with-nx");

const isProd = process.env.NODE_ENV === "production";
console.log("NODE_ENV", isProd);

Here is my config:

module.exports = withPWA(
  withNx({
    pwa: {
      disable: !isProd,
      dest: "public",
    },
    webpack: (config) => {
      config.resolve.alias = {
        ...(config.resolve.alias || {}),
        // Transform all direct `react-native` imports to `react-native-web`
        "react-native$": "react-native-web",
      };
      config.resolve.extensions = [
        ".web.js",
        ".web.ts",
        ".web.tsx",
        ...config.resolve.extensions,
      ];
      return config;
    },
  })
);
```

You need to build the next app for production and run it. Then when you load the home page you get the error if you have images under the `public` directory

# Expected Behaviors

`next-pwa` should correctly handle link to public directory.

# Screenshots

<img width="556" alt="Screen Shot 2020-12-02 at 09 44 28" src="https://user-images.githubusercontent.com/4640135/100849521-fa9e4000-3482-11eb-8c3c-7707f22f5d38.png">

**Comment by dhmacs** [comment]
I should add for context that I'm using [Nx](https://nx.dev/react), but I don't know how it could affect the plugin

**Comment by dhmacs** [comment]
@shadowwalker it looks similar to this issue https://github.com/shadowwalker/next-pwa/issues/80, since Nx stores apps under `apps/my-next-js-app` and the build to `dist/apps/my-next-js-app`.. But I can figure out how to set the `dist` folder to make it work

**Comment by shadowwalker** [comment]
Could you please create a simple error reproduce repo?

**Comment by dhmacs** [comment]
@shadowwalker here it is:
https://github.com/dhmacs/nx-next-pwa-repro

**Comment by JerryGreen** [comment]
Doesn't seem like "minimal reproducible repo", and more like a whole project instead 😂

**Comment by dhmacs** [comment]
@JerryGreen It's literally the result of creating an Nx workspace (i.e. `npx create-nx-workspace`) preconfigured for Next.js and trying to add `next-pwa` to it 😅 All that you see is boilerplate stuff generated by Nx. Nx manages the monorepo and gives you a few opinions about how to organize the project. The problem here, similar to Blitz-js, is that the dist folder is compiled at the root of the project, while the the source code of the next js app is under `apps` folder

**Comment by dhmacs** [comment]
Just to add on this if you don't know Nx, basically what it does is that it lets you create multiple apps into the same workspace (typical example is having both the web apps and mobile apps under the same workspace) and you use the `libs` folder to share code between apps. What I'm testing is using `react-native-web` to build both the web app and React native mobile apps and share as much code as possible between them under the libs folder.

**Comment by shadowwalker** [comment]
@dhmacs
You can fix it by doing following two steps
1. Upgrade `next-pwa` to `5.0.0`
2. Add following config inside here:

https://github.com/dhmacs/nx-next-pwa-repro/blob/74ede253b64c99d6aa923acf980c1a5e18e29b09/apps/web/next.config.js#L10-L14

``` javascript
modifyURLPrefix: {
        '../public': ''
}
```

**Comment by dhmacs** [comment]
Awesome and thanks @shadowwalker ! 👏

**Comment by SarkarKurdish** [comment]
11/22/2001 the issue reappeared in the latest version (next-pwa@5.4.1)

**Comment by leotm** [comment]
same here ^ will share here if/when figure the cause

**Comment by priyansharma** [comment]
(next-pwa@5.4.1) This version have issue update to 5.5.4
