### ISSUE TITLE
start_url does not respond with a 200 when offline

### ISSUE THREAD

**Issue by Ramos-Diego** [shadowwalker/next-pwa#124]
# Summary

It seems that the cache configuration provided in [cache.js](https://github.com/shadowwalker/next-pwa/blob/master/cache.js) is incorrect, causing the error **start_url does not respond with a 200 when offline** in lighthouse. 

# How To Reproduce

1. Go to [pwa-sage.vercel.app](https://pwa-sage.vercel.app/) in Chrome
2. Press CTRL + SHIFT + I and **Generate a report** from the Lighthouse tab
3. Scroll down to Progressive Web App > Fast and reliable

To reproduce the issue you may deploy the example provided by [Next.js](https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app) and repeat the instructions. 

# Expected Behaviors
To get error **start_url does not respond with a 200 when offline** in the report generated by lighthouse.

# Screenshots
![image](https://user-images.githubusercontent.com/57334399/100921880-26352080-34ab-11eb-9ab7-22d48e70ebda.png)

# Additional Context

This same issue seems to have been resolved for another app, but I was unable to implement that solution. 

See **[Fix with-next-offline example caching #9900](https://github.com/vercel/next.js/pull/9900)**

**Comment by shadowwalker** [comment]
Duplicate https://github.com/shadowwalker/next-pwa/issues/107

**Comment by shadowwalker** [comment]
![image](https://user-images.githubusercontent.com/9603375/100972448-ae3c1a00-34ed-11eb-81ca-ec8fde7654a9.png)

**Comment by Ramos-Diego** [comment]
Thanks. I just started using Lighthouse and realized after a lot of testing that I need to take its results with a grain of salt. They are not totally consistent.
