### ISSUE TITLE
PWA config initializes twice

### ISSUE THREAD

**Issue by JerryGreen** [shadowwalker/next-pwa#125]
## Summary

```sh
$ yarn dev
yarn run v1.22.4
warning package.json: No license field
$ next dev
Loaded env from C:\Users\Jerry\projects\jerrygreen.me\.env
ready - started server on http://localhost:3000
> [PWA] PWA support is disabled # <--- this
> [PWA] PWA support is disabled # <--- runs twice
event - compiled successfully
```

## How To Reproduce

I'm not sure if it's complete environment requirement to reproduce, but seems it is. I have this simplest `next.config.js`:

```js
const withPWA = require('next-pwa')

module.exports = withPWA({
  pwa: { disable: process.env.NODE_ENV !== 'production' },
})
```

## Expected Behaviors

Run initialization code only once.

**Comment by shadowwalker** [comment]
That's just logging, you can just ignore it.
One print for server side build
One print for client side build

**Comment by JerryGreen** [comment]
That's still a bit weird, but ok..
