### ISSUE TITLE
Cannot register service worker with minimal configuration on Netlify

### ISSUE THREAD

**Issue by dackers86** [shadowwalker/next-pwa#13]
Error message in the console shows....

SW registration failed: TypeError: Failed to register a ServiceWorker for scope ('https://stupefied-franklin-ead670.netlify.com/') with script ('https://stupefied-franklin-ead670.netlify.com/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.

The build files generate and SW.js, rather than a service-worker.js.

Could there be some additional configuration I am missing?

**Comment by dackers86** [comment]
NextJS config is...

```
const path = require('path');

module.exports = withPWA({
  pwa: {
    dest: 'public',
  },
  webpack(config, options) {
    config.resolve.alias['~'] = path.join(__dirname, './');
    return config;
  },
});
```

**Comment by dackers86** [comment]
Lighthouse details...

![image](https://user-images.githubusercontent.com/2060661/74737988-e53a8b00-524d-11ea-8181-bc6d57e935c9.png)

**Comment by dackers86** [comment]
Fixed!

To solve the issue, I ran a local build and copied the files to a folder called public/static.
In addition place your manifest.json into the folder.

You should now have something like...

public/static/manifest.json
public/static/service-worker.js
public/static/workbox-*.js


Add the followng redirects in your netlify.toml file...

[[redirects]]
  from = "/service-worker.js"
  to = "/static/service-worker.js"
  status = 200

[[redirects]]
  from = "/workbox-07643d7a.js"
  to = "/static/workbox-07643d7a.js"
  status = 200

  [[redirects]]
  from = "/manifest.json"
  to = "/static/manifest.json"
  status = 200

Finally, your next config should include the following...

pwa: {
    dest: 'public/static',
    sw: 'service-worker.js',
  },

**Comment by shadowwalker** [comment]
I saw your website is currently working fine. I assume you manually change the `sw.js` file name to `service-worker.js` ?
If you wish to keep it simple and use `sw.js`, try `clear site data` button and do a hard reload.
![image](https://user-images.githubusercontent.com/9603375/74774044-e4065f80-5247-11ea-8e85-ab9257495e6c.png)

**Comment by shadowwalker** [comment]
Glad you got it solved. But I would suggest that you don't need `static` folder inside your `public` folder and won't need to copy them manually if you hosted in `public` from root path. And you could save those redirects as well.

**Comment by dackers86** [comment]
Thanks @shadowwalker.

I've re-opened as my issue started to re-occur on my next build.

I have applied the above changes but now seem to get the following error...

workbox-07643d7a.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://stupefied-franklin-ead670.netlify.com/_next/static/fwDdo8LU9qWNJYmm2pO_S/_buildManifest.js","status":404}]
    at D (https://stupefied-franklin-ead670.netlify.com/workbox-07643d7a.js:1:11361)
    at async Promise.all (index 2)
    at async D.install (https://stupefied-franklin-ead670.netlify.com/workbox-07643d7a.js:1:10780)

Do you know what this could be?

**Comment by dackers86** [comment]
My config now looks like....

Netlify.toml
```
[[redirects]]
  from = "/service-worker.js"
  to = "/sw.js"
  status = 200

```

Nect config
```
module.exports = withPWA({
  pwa: {
    dest: 'public/',
  },
  webpack(config, options) {
    config.resolve.alias['~'] = path.join(__dirname, './');
    return config;
  },
});
```

And I **no longer** commit sw.js and workbox-*.js


Lighthouse will show the above issues for 200 offline. Could this be an issue similar too offline-next? https://github.com/zeit/next.js/pull/9900

**Comment by dackers86** [comment]
HI @shadowwalker.

Apologies for the bother on this one. It turns out the issue (and inconsistency) was left over code from next-offline.

```
import { register, unregister } from "next-offline/runtime";

const App = ({ Component, pageProps }) => {
  useEffect(() => {
    register();

    return unregister();
  }, []);
```

It was most likely overwriting when the service worker when the component was mounted. 

Hope this helps anyone migrating or using different versions of next-offline

**Comment by JerryGreen** [comment]
@dackers86 you used both `next-pwa` AND `next-offline`? Don't they serve the same single purpose?

**Comment by dackers86** [comment]
Hi @JerryGreen 

I seem to have got confused initially.

I now only use **next-pwa,**  and my website is now working as expected
