### ISSUE TITLE
Error with version 5.0.1 : "runtimeCaching" is not allowed

### ISSUE THREAD

**Issue by vinaykarode** [shadowwalker/next-pwa#136]
# Summary
Running `next-pwa/examples/offline-fallback/` with `"next-pwa": "5.0.1"` produces this error (works fine with `"next-pwa": "5.0.0"`)

```
Please check your InjectManifest plugin configuration:
"runtimeCaching" is not allowed
```

# How To Reproduce

1. download the example `https://github.com/shadowwalker/next-pwa/tree/master/examples/offline-fallback`
2. Run `npm install`
3. Run `npm run build`

**Comment by shadowwalker** [comment]
version `5.0.2` should be able to fix it
