### ISSUE TITLE
Integrate with another 3rd party service worker

### ISSUE THREAD

**Issue by flamedmg** [shadowwalker/next-pwa#141]
Could you please advice how to integrate 3rd party service worker for web push into next-pwa enabled website?

**Comment by shadowwalker** [comment]
Have you checkout this example: https://github.com/shadowwalker/next-pwa/tree/master/examples/web-push

Is this what you need?

**Comment by flamedmg** [comment]
@shadowwalker apparently no. I tried to use it in few ways. Put there 3rd party code and try to import their js, but it doesn't work.
Here is integration i'm talking about. I found that most 3rd parties are not flexible at all in integration with other service workers. Could you please advice how i can merry them both?!

**Comment by LucasMallmann** [comment]
Hey, @flamedmg  this might be a late answer, but anyway.

In order to integrate the next-pwa service worker with the OneSignal service worker, all you have to do is to import your service worker on the top of your OneSignalSDKWorker.js file.

But you have to keep in mind that you must register the OneSignalSDKWorker file, and not the next-pwa service worker. Let me show u an example:

```js
// In your OneSignalSDKWorker.js and OneSignalSDKUpdaterWorker.js
// @see https://documentation.onesignal.com/docs/onesignal-service-worker-faq#integrating-multiple-service-workers
importScripts(`${self.origin}/sw.js`); // this is your custom service worker generated by next-pwa
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');
```

```js
// next.config.js
const withPWA = require('next-pwa')
const runtimeCaching = require('next-pwa/cache')

module.exports = withPWA({
  pwa: {
    dest: 'public',
    runtimeCaching,
    register: false // you have to keep it false in order to register the onesignal sw.
  },
})
```

```jsx
// _app.js file or `index.js` page. Whatever you want to register your sw.
function App() {
  useEffect(() => {
    if (navigator.serviceWorker) {
      navigator.serviceWorker.register(
          `${basePath}/OneSignalSDKWorker.js`
      ).then(reg => console.log(reg));
    }
  }, [])

  return (...)
}

```

**Comment by shadowwalker** [comment]
You might want checkout the option `importScripts` in `pwa` config as well.

Reference: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#GenerateSW

![image](https://user-images.githubusercontent.com/9603375/106991099-6a9ea000-672a-11eb-83f3-d4c80a40427d.png)

**Comment by mstankov** [comment]
> You might want checkout the option `importScripts` in `pwa` config as well.
> 
> Reference: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#GenerateSW
> 
> ![image](https://user-images.githubusercontent.com/9603375/106991099-6a9ea000-672a-11eb-83f3-d4c80a40427d.png)

Hi mate, considering OneSignal's service worker overwrites any other service registered on the root scope, perhaps we should stick to integrating `sw.js` into the 3rd party (OneSignal) via `importScripts` like @LucasMallmann has suggested? This thread is over a year old now, maybe things have changed since then though :))

**Comment by reymon359** [comment]
Hey @mstankov (and others like me who were looking for a solution 😄) you are right that things have changed, actually, the  
Integrating Multiple Service Workers solution has been deprecated. 
<img width="671" alt="Screenshot 2022-06-19 at 19 24 51" src="https://user-images.githubusercontent.com/31936665/174483501-73a706f7-a0fa-4327-b4e3-4edd1a718e42.png">

I followed the steps from here
<img width="656" alt="Screenshot 2022-06-19 at 21 28 04" src="https://user-images.githubusercontent.com/31936665/174483977-79890128-8c89-4ed1-846a-68173da06934.png">

<img width="262" alt="Screenshot 2022-06-19 at 21 37 27" src="https://user-images.githubusercontent.com/31936665/174484005-18b647ad-6cdf-4245-90d7-acf7edbe051a.png">


and updated the config in my app like this
<img width="554" alt="Screenshot 2022-06-19 at 21 29 19" src="https://user-images.githubusercontent.com/31936665/174483535-f363c6a7-7a88-4dba-a60f-a1ae0f8db3c3.png">

And it worked successfully. Hope the above helps someone else 😄

**Comment by bruceharrison1984** [comment]
To add to @reymon359 answer, if you're using `react-onesignal` you can initialize the service worked by using the following in your `_app.tsx` or layout file.

No other code changes necessary, just make sure to place the service worker file where @reymon359 noted.

```jsx
  useEffect(() => {
    OneSignal.init({
      appId: process.env.NEXT_PUBLIC_ONESIGNAL_APP_ID!,
      safari_web_id: process.env.NEXT_PUBLIC_ONESIGNAL_SAFARI_WEB_ID!,
      allowLocalhostAsSecureOrigin: process.env.NODE_ENV === 'development',
      serviceWorkerParam: {
        scope: '/js/push/onesignal/',
      },
      serviceWorkerPath: './js/push/onesignal/OneSignalSDKWorker.js',
    });
  }, []);
```
It still acts kinda weird sometimes depending on if notifications are enabled on the page, but this seems to be an issue with OneSignal, and not next-pwa.

**Comment by reymon359** [comment]
Thanks for the tip @bruceharrison1984, didn't know you could add that service worker config on the init method 😄 

Btw, I may be wrong, I think you are missing the `serviceWorkerUpdaterPath` above, It should be something like this:
```ts
  useEffect(() => {
    OneSignal.init({
      appId: process.env.NEXT_PUBLIC_ONESIGNAL_APP_ID!,
      safari_web_id: process.env.NEXT_PUBLIC_ONESIGNAL_SAFARI_WEB_ID!,
      allowLocalhostAsSecureOrigin: process.env.NODE_ENV === 'development',
      serviceWorkerParam: {
        scope: '/js/push/onesignal/',
      },
      serviceWorkerPath: './js/push/onesignal/OneSignalSDKWorker.js',
      serviceWorkerUpdaterPath: '/js/push/onesignal/OneSignalSDKUpdaterWorker.js',
    });
  }, []);

```

**Comment by bruceharrison1984** [comment]
@reymon359 Good catch, I do need to update `serviceWorkerUpdaterPath`, but in my case it should be the same path as `serviceWorkerPath`. 

This is because OneSignal deprecated the `OneSignalSDKUpdaterWorker` for any integrations that have occured since November 22, 2021.

https://documentation.onesignal.com/docs/web-push-quickstart#hosting-the-file

**Comment by reymon359** [comment]
> This is because OneSignal deprecated the OneSignalSDKUpdaterWorker for any integrations that have occured since November 22, 2021. Since my integration is only a few weeks old, I don't need to mess with both files.
https://documentation.onesignal.com/docs/web-push-quickstart#hosting-the-file

@bruceharrison1984 I didn't know about it and looks like I don't need the `OneSignalSDKUpdaterWorker`. 

 Thanks for sharing that info! 😄
