### ISSUE TITLE
Is there a way to enable full service worker in dev mode?

### ISSUE THREAD

**Issue by aboodman** [shadowwalker/next-pwa#143]
When I use next-pwa in dev mode, I get the following message during build:

```
> [PWA] Build in develop mode, cache and precache are mostly disabled. This means offline support is disabled, but you can continue developing other functions in service worker.
```

... and sure enough, none of my service worker entries are generated. I get why this is as it is, if the ServiceWorker is being used as more of an optimization.

But for apps that are trying to be truly offline-first, it's difficult to developer if the service worker isn't running as it will be in production.

Is there a way to get the service worker to be generated as normal in dev mode?

**Comment by jgartor** [comment]
Readme mentions this, but it seems like not working:

> Force next-pwa to generate worker box production build by specify the option mode: 'production' in your pwa section of next.config.js.

**Comment by shadowwalker** [comment]
When you want to test offline of the web app, simply use `yarn start` instead of `yarn dev`.
