### ISSUE TITLE
Workbox worker always using NetworkOnly strategy to fetch data

### ISSUE THREAD

**Issue by Edqe14** [shadowwalker/next-pwa#148]
Hello,
I'm currently trying to make the PWA I'm making offline capable but no matter I set `runtimeCaching` on `next.config.js`, it still fetching data using `NetworkOnly` strategy on any path.

![image](https://user-images.githubusercontent.com/34704796/105960685-28cd8400-60b0-11eb-939a-20232f6b4be5.png)

next.config.js
```js
const withPWA = require('next-pwa');

module.exports = withPWA({
  distDir: 'dist',
  dir: './src',
  pwa: {
    dest: 'public',
    cleanupOutdatedCaches: true,
    runtimeCaching: [
      {
        urlPattern: '/',
        handler: 'NetworkFirst',
        options: {
          cacheName: 'start-url'
        }
      },
      {
        urlPattern: /\/assets\/.*/i,
        handler: 'CacheFirst'
      },
      {
        urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
        handler: 'CacheFirst',
        options: {
          cacheName: 'google-fonts'
        }
      },
      {
        urlPattern: /\/api\/.*$/i,
        handler: 'NetworkOnly'
      }
    ]
  },
  async redirects () {
    return [
      {
        source: '/support',
        destination: '--url--',
        permanent: true
      }
    ];
  }
});
```

Any help is appreciated. Thanks!

**Comment by marcofranssen** [comment]
Experiencing the same issue. On my vercel deployment opening in Google Chrome, fails to register the service worker. On localhost service worker registers successfully, but when switching to offline mode, non of the pages are displayed.

**Comment by Edqe14** [comment]
It seems runtime caching is disabled on development build [#150](https://github.com/shadowwalker/next-pwa/issues/150#issuecomment-769349621). Closing this issue for now.
