### ISSUE TITLE
How to integrate next-pwa with SASS?

### ISSUE THREAD

**Issue by TrejoCode** [shadowwalker/next-pwa#15]
Hi, I have a compilation error because I can't find how to integrate next.config with my next sass, can you help me a little? Thank you.

``` js
const withPWA       = require('next-pwa');
const withSass      = require('@zeit/next-sass');
module.exports      = withPWA(withSass());
```

This returns me a sass error:
```
Module parse failed: Unexpected character '@' (2:0)
```

Maybe it's a mistake of mine, but I haven't managed to insert multiple configurations to my next.config

**Comment by shadowwalker** [comment]
change `withPWA(withSass())` to `withPWA(withSass({}))`

**Comment by TrejoCode** [comment]
> change `withPWA(withSass())` to `withPWA(withSass({}))`

Thank you, today i will try it and comment to you

**Comment by TrejoCode** [comment]
@shadowwalker Thank you, still fail i have the same error.
But, i'll try with 'next-compose-plugins' for manage multiplies 'exports'

**Comment by TrejoCode** [comment]
My solution was:
1. Install 'next-compose-plugins'
2. In 'next.config':
``` js
const withPlugins   = require('next-compose-plugins');
const PWA           = require('next-pwa');
const sass          = require('@zeit/next-sass');

module.exports      = withPlugins([PWA, sass]);
```
