### ISSUE TITLE
Allow workbox debug logging in prod and allow runtimeCaching in dev

### ISSUE THREAD

**Issue by marcofranssen** [shadowwalker/next-pwa#150]
To be able to debug and properly test my custom runtimeCaching rules I need to have the following 2 capabilities.

- [ ] Debug logging in production build
- [ ] Enabling runtimeCaching rules in development build

Using the first option I can test the routing and verify in the console if my caching rules properly apply to the production build..

Using the second option I can test my custome runtimeCaching rules during development.

I'm currently trying to replicate the setting I used on my hexo blog. https://marcofranssen.nl
In this service worker I'm caching the first 5 blogposts and I'm caching the pages in the top menu. By doing so I allow my readers to read my pages and most recent 5 blogposts offline.

Now I'm trying to customize the caching behavior to replicate this functionality, but current `next-pwa` makes it almost impossible to debug this.

See here my attempt to customize the runtimeConfig. I think I still miss out on some urls in the first expression, but don't have any logs available to test this out in production, neither can replicate in development due to the fact the runtimeCaching is ignored. Having both these options allows me to test both in dev and prod.

```js
  pwa: {
    dest: "public",
    runtimeCaching: runtimeCaching.concat([
      {
        urlPattern: /\/_next\/static\/chunks\/pages\/.*\.js.*$/i,
        handler: "StaleWhileRevalidate",
        options: {
          cacheName: "page-content",
          expiration: {
            maxEntries: 32,
            maxAgeSeconds: 24 * 60 * 60, // 24 hours
          },
        },
      },
      {
        urlPattern: /\/_next\/image?url=.*$/i,
        handler: "StaleWhileRevalidate",
        options: {
          cacheName: "next-image",
          expiration: {
            maxEntries: 32,
            maxAgeSeconds: 24 * 60 * 60, // 24 hours
          },
        },
      },
      {
        urlPattern: /^https:\/\/www\.google-analytics\.com\/.*/i,
        handler: "NetworkOnly",
      },
      {
        urlPattern: /^https:\/\/pagead2\.googlesyndication\.com\/.*/i,
        handler: "NetworkOnly",
      },
    ]),
  },
```

Please let me know if a PR would be accepted for this?

**Comment by cullylarson** [comment]
@marcofranssen  If you just want to do this temporarily, you could directly edit the package code in your `node_modules` folder. It would at least let you debug until an update to the package is made. This is the line you'd want to change: https://github.com/shadowwalker/next-pwa/blob/master/index.js#L253

Instead of `dev ? ...`, change it to `(false) ? ...`.

**Comment by marcofranssen** [comment]
@cullylarson yes I figured that out as well, but to make it easier for all users, I think both features should be added to this package. Especially logging in a prod build would be awesome to test without the webpack autoreloading network traffic.

**Comment by cullylarson** [comment]
I wonder if adding a config option named `devOptions` or something would be a good idea. The value would be a set of flags to turn on/off various things in dev mode. It would make it easy to add other flags in the future. For example:

```js
pwa: {
    register: true,
    scope: '/app',
    devOptions: {
      overrideRuntimeCache: true, // default
      overrideManifestEntries: true,
      ignoreTsUrls: true,
    },
  }
```

Or could add an `isDev` option to override the `dev` value.

**Comment by shadowwalker** [comment]
> Debug logging in production build

Have you try to add following in the `pwa` config?

``` javascript
pwa: {
  mode: 'development',
  ....
}
```
