### ISSUE TITLE
PWA is not installable

### ISSUE THREAD

**Issue by marcofranssen** [shadowwalker/next-pwa#152]
# Summary

The install button is not shown in the webbrowser. Although Lighthouse reports all is good. See here for the criteria that makes an PWA installable. https://web.dev/install-criteria/

# How To Reproduce

The new version of my blog doesn't show the install button despite lighthouse reports it should be installable.

1. Navigate to https://nextjs.marcofranssen.nl/
2. See there is no install button as shown in expected behaviors.

# Expected Behaviors

The browser shows a install button in top right of the address bar. 

See e.g. https://marcofranssen.nl

<img width="630" alt="Screenshot 2021-01-31 at 21 10 18" src="https://user-images.githubusercontent.com/694733/106396590-28631f00-6409-11eb-8353-a1d97181d2f1.png">

# Additional Context

Running on MacOS big Sur and Google Chrome.

**Comment by shadowwalker** [comment]
You are missing a `"start_url": "/"` in your `site.webmanifest` file.

**Comment by marcofranssen** [comment]
Thanks for the answer. Indeed missed the `start_url` although lighthouse reported all was correctly in place. I filed a bug with lighthouse as well.
