### ISSUE TITLE
next-pwa compiled with no error but service worker is not working with webpack <= 4

### ISSUE THREAD

**Issue by sugar3103** [shadowwalker/next-pwa#154]
> This is a know issue with workbox-webpack-plugin, can you try the following before build:
> 
> ```
> yarn remove webpack
> yarn add -D webpack@webpack-4
> ```

Hi @shadowwalker , i have tested it with your suggestion, the compiler compile with no error but the service worker is not working when i Ctrl+C to stop the yarn run dev script. 
Enviroment :
"dependencies": {
    "next": "^10.0.6",
    "next-pwa": "^5.0.5",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "webpack": "^4.46.0"
  }
Step to reproduce : 
yarn 
yarn run dev -> (localhost:3000 working with no problem)
Ctrl+C 
localhost:3000 showing "This site can't be reached" 

expected bahaviour:
yarn 
yarn run dev -> (localhost:3000 working with no problem)
Ctrl+C 
localhost:3000 working with cached content

_Originally posted by @sugar3103 in https://github.com/shadowwalker/next-pwa/issues/153#issuecomment-772270703_

**Comment by shadowwalker** [comment]
Try yarn start. In development, offline is disabled by design.

**Comment by sugar3103** [comment]
It worked as expected but yarn start is for production build only and do NOT have hot reload. But that's ok cause for the purpose of PWA is for production only. Greats!
It would be greater (better) if you could make it support webpack > 5 (for future update ofc)
thank you very much
