### ISSUE TITLE
next-pwa is not generating sw.js by default with next js 10 and latest version of next-pwa

### ISSUE THREAD

**Issue by S3gillu** [shadowwalker/next-pwa#155]
# Summary

I am trying to configure PWA feature in my Next.js v10 application but after following the reference example steps I was getting the issue that 'service was no registered post npm run build command'

# How To Reproduce

Steps to reproduce the behaviour:

1. Go to [https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app](https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app)

 go to this repo and clone it. After cloning, run npm install and then try run this command `npm run build` or `yarn build`.

2. check for .next folder, there will be no sw.js file, which should be there as per the documentation
3. run lighthouse audit and you will see 'no service worker registered'

# Expected Behaviors

next-PWA should register sw.js by default without the need of any custom server configuration

**Comment by LucasMallmann** [comment]
The URL you wrote is taking to an issue page with no results found 🤔 
![image](https://user-images.githubusercontent.com/23031413/106820019-6d7d9000-6659-11eb-96cc-68db86c6d178.png)

**Comment by S3gillu** [comment]
@LucasMallmann Somehow gitpod url was not working, I have updated the link with GitHub repository for next-pwa with next js example. Please look into it

**Comment by LucasMallmann** [comment]
Oh, now I could see the example. In the example, there is a `next.config.js` file with some configuration for the `next-pwa` package. In this config file, the service worker destination is pointing to the `/public` folder, so that's why you did not find the service worker inside the .next folder since it's not its destination.|

This is a print from my console log:
```bash
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /Users/lucas/Projects/Open-Source/progressive-web-app/node_modules/next-pwa/register.js
> [PWA] Service worker: /Users/lucas/Projects/Open-Source/progressive-web-app/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Compile server
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (2/2)
info  - Finalizing page optimization  
```

When I run `npm run build`, it generates the service worker inside the /public folder.
![image](https://user-images.githubusercontent.com/23031413/106982280-8b72ef80-6742-11eb-97f2-4692ee3095b7.png)

And also the service worker is registered when I run `npm run start`:
![image](https://user-images.githubusercontent.com/23031413/106982325-a34a7380-6742-11eb-9c6a-ad5a1f260134.png)


All I did was to start a project using the repo you sent.

**Comment by shadowwalker** [comment]
The example works fine, please revalidate if the issue is still there.

**Comment by S3gillu** [comment]
@LucasMallmann Thank you for the explanation but somehow I am not able to see this generated services-worker file called sw.js inside my public folder even after running production build. I have tried the same configuration as per the documentation. Either way, thank you for the support. Cheers !!

**Comment by wadehammes** [comment]
I am having the same issue. 

Next version: 10.0.9
Node: 14.x

I am using `next-compose-plugins` like so in my `next.config.js`:

```
const nextConfig = {
  pwa: {
    disable: process.env.ENVIRONMENT === "local",
  },
  ...otherConfig
};

module.exports = withPlugins(
  [[withPWA], [withFonts], [withOptimizedImages], [withSourceMaps]],
  nextConfig,
);
```

I can see the PWA step in the build working on Vercel:
![image](https://user-images.githubusercontent.com/222170/112509737-206b8f80-8d67-11eb-86c3-e8aed1a560c3.png)

but the output of the source contains no sw.js:
![image](https://user-images.githubusercontent.com/222170/112509941-56a90f00-8d67-11eb-8862-9b6dfd826261.png)

**Comment by S3gillu** [comment]
This issue has been fixed, it's like next-pwa was not exporting all the other wrapped config which was in next-config.js in my case. Thank you everyone for all the support. Appreciated!! Closing this issue now
