### ISSUE TITLE
How to get ServiceWorkerRegistration object?

### ISSUE THREAD

**Issue by iarmankhan** [shadowwalker/next-pwa#156]
# Summary

I'm currently trying to implement FCM in my PWA and from the firebase docs it is said to have service worker with exactly name `firebase-messaging-sw.js` or to provide a ServiceWorkerRegistration object to getToken method.

Now, I can use the sw parameter in next-pwa to rename the output file and it is working but I think it would be better if I can get the object instead of renaming the whole file just for one thing.

Firebase getToken documentation: [Here](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#gettoken)

Thank you

**Comment by shadowwalker** [comment]
You can use this to get the registration object

```javascript
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  console.log(registration)
} })
```
