### ISSUE TITLE
next-pwa causing "tapPromise" undefined error

### ISSUE THREAD

**Issue by helloitsm3** [shadowwalker/next-pwa#158]
# Summary

next-pwa is causing "tapPromise" undefined error when trying to build the web application

# How To Reproduce

1. Install latest Next.js
2. Install latest webpack
3. Try building the application by running `npm build` or `yarn build`

# Screenshots
![image](https://user-images.githubusercontent.com/13825491/107169068-ef720e00-69f7-11eb-8026-3e663272c938.png)

**Comment by LucasMallmann** [comment]
Hi @helloitsm3 . This might be a duplicated from #138  and also #140 . In summary, I think this is an issue with webpack as it's written in this comment from one of the issues above: https://github.com/shadowwalker/next-pwa/issues/138#issuecomment-762603877

**Comment by helloitsm3** [comment]
> Hi @helloitsm3 . This might be a duplicated from #138 and also #140 . In summary, I think this is an issue with webpack as it's written in this comment from one of the issues above: [#138 (comment)](https://github.com/shadowwalker/next-pwa/issues/138#issuecomment-762603877)

Yes, it has something to do with Webpack since I have to downgrade webpack for it to work.

**Comment by xstable** [comment]
@helloitsm3 can you describe what you did exactly?

**Comment by helloitsm3** [comment]
> @helloitsm3 can you describe what you did exactly?

I didn't do much. All I did was using the latest `nextjs` and the latest `next-pwa` and it throws me a "webpack: not found" error. After adding `webpack@5.21.2`, it throws me this error.

**Comment by xstable** [comment]
I also found only the solution to hard-pin the nextjs to 10.0.5 for now.

**Comment by helloitsm3** [comment]
> I also found only the solution to hard-pin the nextjs to 10.0.5 for now.

I think this issue is only happening on 10.0.6. I have other projects that is using 10.0.5 and it seems to be working fine

**Comment by andrewtremblay** [comment]
I see it happening as well in 10.0.7

**Comment by helloitsm3** [comment]
> I see it happening as well in 10.0.7

Probably because it doesn't support we pack 5 now which is why it's having this issue for NextJS 10+

**Comment by shadowwalker** [comment]
Upgrade to both latest version of `next.js` and `next-pwa` now should fix the problem
