### ISSUE TITLE
New version 2.1.3 causes error with dotenv in dev mode (PWA disabled)

### ISSUE THREAD

**Issue by haoict** [shadowwalker/next-pwa#16]
As I have been following this project from version 2.1.2, everything works just fine.
But after upgrading to version 2.1.3, I have this error only in dev mode (PWA suppport is disabled)
```
Module not found: Can't resolve 'fs' in '..../node_modules/dotenv/lib'
```

Production mode is okay. Could you check it?

`next.config.js` (no custom webpack config)
```
withPWA({
      pwa: {
        register: false,
        skipWaiting: false,
        dest: 'public'
      },
    })
```

```
"dotenv": "^8.2.0",
"next": "^9.2.0",
"next-pwa": "^2.1.3",
```

**Comment by shadowwalker** [comment]
How did you import dotenv? This doesn't seem an issue with next-pwa

**Comment by haoict** [comment]
I'm using dotenv in custom express server for next.js.

Let me try to create a reproduce project

**Comment by haoict** [comment]
I can not manage to create it this time. Close for now.

**Comment by haoict** [comment]
Just to let you know that version `2.2.0` works for me again :)

**Comment by shadowwalker** [comment]
@haoict Best thing you could have is getting things fixed magically and automatically.
