### ISSUE TITLE
Feature Request: Enable opt out of start-url requirement when providing runtime caching 

### ISSUE THREAD

**Issue by tatethurston** [shadowwalker/next-pwa#161]
# Summary

I'd like to propose introducing a configuration option to override the need for this exception: https://github.com/shadowwalker/next-pwa/blob/master/index.js#L60-L63.

Specifically, I'd like to propose introducing an optional `startUrl` to next-pwa's top level configuration. When a value is present, that value will be used instead of `runtimeCaching[0].urlPattern` and the exception will not be raised.

If you're open to this idea, I'm happy to PR the work and update the documentation so we can look at a concrete proposal.

# How To Reproduce

1. Provide `runtimeCaching` options
2. Don't provide [this](https://github.com/shadowwalker/next-pwa/blob/0e9fb5850678a98b0ee0f96d468bd7c558006030/cache.js#L4-L14) as the first entry in `runtimeCaching`

# Additional Context

Presently, my configuration looks like this:

```
  runtimeCaching: [
    {
      // The below is required by next-pwa
      // https://github.com/shadowwalker/next-pwa/blob/master/cache.js#L4-L5
      urlPattern: '/this-is-not-used-but-next-pwa-requires-it',
      handler: 'NetworkOnly',
      options: {
        cacheName: 'start-url',
      },
    },
    ...
    {
      urlPattern: (eventHolder) =>
        eventHolder.event.request.mode === 'navigate',
      handler: 'NetworkOnly',
      options: {
        precacheFallback: {
          fallbackURL: OFFLINE_FALLBACK_PAGE,
        },
      },
    },
```

It would be great to remove the need for the first entry in `runtimeCaching`. I created a silly debugging rabbit hole for myself by setting the `urlPattern` to `/` for the first entry which caused my `fallbackURL` not to apply and I chased through workbox before I finally realized my mistake.

Related issues:
https://github.com/shadowwalker/next-pwa/issues/120

**Comment by tatethurston** [comment]
Apologies for the `bug` label -- this should be `feature` or `question`

**Comment by yashSangai** [comment]
A related issue on Safari:
#131 

For #120, even after putting the NetworkFirst strategy, it shows the content of the login page in Safari. @shadowwalker

**Comment by tatethurston** [comment]
@shadowwalker Any particular reason for closing this?

**Comment by shadowwalker** [comment]
@tatethurston This behavior has changed as I figure out some better way to handle start url use cases.

**Comment by yashSangai** [comment]
@shadowwalker Please brief us on your approach!

**Comment by ecam900** [comment]
I'm having the same issue. I'm using Firebase Auth.

My runtimeCache.js is as follows:
`'use strict';

// Workbox RuntimeCaching config: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry
module.exports = [
  {
    urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
    handler: 'StaleWhileRevalidate',
    options: {
      cacheName: 'google-fonts',
      expiration: {
        maxEntries: 4,
        maxAgeSeconds: 1 * 24 * 60 * 60, // 1 days
      },
    },
  },
  {
    urlPattern: /\.(?:eot|otf|ttc|ttf|woff|woff2|font.css)$/i,
    handler: 'StaleWhileRevalidate',
    options: {
      cacheName: 'static-font-assets',
      expiration: {
        maxEntries: 4,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      },
    },
  },
  {
    urlPattern: /\.(?:jpg|jpeg|gif|png|svg|ico|webp)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-image-assets',
      expiration: {
        maxEntries: 64,
        maxAgeSeconds: 0.5 * 60 * 60, // 30m
      },
    },
  },
  {
    urlPattern: /\.(?:mp3|mp4)$/i,
    handler: 'StaleWhileRevalidate',
    options: {
      cacheName: 'static-media-assets',
      expiration: {
        maxEntries: 64,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
    },
  },
  {
    urlPattern: /\.(?:js)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-js-assets',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 1 * 60 * 60, // 1 hours
      },
    },
  },
  {
    urlPattern: /\.(?:css|less)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-style-assets',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
    },
  },
  {
    urlPattern: /\.(?:json|xml|csv)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-data-assets',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 1 * 60 * 60, // 1 hour
      },
    },
  },
  {
    urlPattern: /\/api\/.*$/i,
    handler: 'NetworkFirst',
    method: 'GET',
    options: {
      cacheName: 'apis',
      expiration: {
        maxEntries: 16,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
      networkTimeoutSeconds: 10, // fall back to cache if api does not response within 10 seconds
    },
  },
  {
    urlPattern: /.*/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'others',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
      networkTimeoutSeconds: 10,
    },
  },
];
`

**Comment by ecam900** [comment]
I'm having the same issue. I'm using Firebase Auth.

Here's my next.config:

````javascript
const withPWA = require('next-pwa');
const customRuntimeCache = require('./customRuntimeCache');

module.exports = withPWA({
  pwa: {
    dest: 'public',
    register: false,
    skipWaiting: false,
    runtimeCaching: customRuntimeCache,
    disable: process.env.NODE_ENV === 'development',
  },
  images: {
    deviceSizes: [320, 420, 768, 1024, 1200],
    iconSizes: [],
    domains: [
      'firebasestorage.googleapis.com',
      'localhost:3000',
      'images.prismic.io',
    ],
    path: '/_next/image',
    loader: 'default',
  },
  future: {
    webpack5: true,
  },
});

````


Here's my runtimecache.js:

```javascript
'use strict';

// Workbox RuntimeCaching config: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry
module.exports = [
  {
    urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
    handler: 'StaleWhileRevalidate',
    options: {
      cacheName: 'google-fonts',
      expiration: {
        maxEntries: 4,
        maxAgeSeconds: 1 * 24 * 60 * 60, // 1 days
      },
    },
  },
  {
    urlPattern: /\.(?:eot|otf|ttc|ttf|woff|woff2|font.css)$/i,
    handler: 'StaleWhileRevalidate',
    options: {
      cacheName: 'static-font-assets',
      expiration: {
        maxEntries: 4,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      },
    },
  },
  {
    urlPattern: /\.(?:jpg|jpeg|gif|png|svg|ico|webp)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-image-assets',
      expiration: {
        maxEntries: 64,
        maxAgeSeconds: 0.5 * 60 * 60, // 30m
      },
    },
  },
  {
    urlPattern: /\.(?:mp3|mp4)$/i,
    handler: 'StaleWhileRevalidate',
    options: {
      cacheName: 'static-media-assets',
      expiration: {
        maxEntries: 64,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
    },
  },
  {
    urlPattern: /\.(?:js)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-js-assets',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 1 * 60 * 60, // 1 hours
      },
    },
  },
  {
    urlPattern: /\.(?:css|less)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-style-assets',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
    },
  },
  {
    urlPattern: /\.(?:json|xml|csv)$/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'static-data-assets',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 1 * 60 * 60, // 1 hour
      },
    },
  },
  {
    urlPattern: /\/api\/.*$/i,
    handler: 'NetworkFirst',
    method: 'GET',
    options: {
      cacheName: 'apis',
      expiration: {
        maxEntries: 16,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
      networkTimeoutSeconds: 10, // fall back to cache if api does not response within 10 seconds
    },
  },
  {
    urlPattern: /.*/i,
    handler: 'NetworkFirst',
    options: {
      cacheName: 'others',
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
      networkTimeoutSeconds: 10,
    },
  },
];

````

**Comment by shadowwalker** [comment]
@ecam900 Can you create a new issue for that?

**Comment by ecam900** [comment]
Yes sir, will do.

Also thanks for writing this package.

**Comment by aguilarm** [comment]
This error still throws if you use a custom runtimeCache without start-url, which it seems should no longer be the case because of dynamicStartUrl? 

Just fyi, it seems like this is still WIP so I'm going to go ahead and add a start-url cache key but the current default runtime-cache.js does not appear to work on the most recent version via npm. Could be that I'm jumping the gun a little.
