### ISSUE TITLE
Can't find variable: caches  next-pwa/register.js:8:23

### ISSUE THREAD

**Issue by Cherchercher** [shadowwalker/next-pwa#164]
User click events: 

ReferenceError: Can't find variable: caches
  at ? (webpack://_N_E/./node_modules/next-pwa/register.js:8:23)
  at asyncFunctionResume([native code])
  at dispatchEvent(webpack://_N_E/./node_modules/workbox-window/build/workbox-window.prod.es5.mjs:1:4234)
  at apply(webpack://_N_E/./node_modules/workbox-window/build/workbox-window.prod.es5.mjs:1:1243)
  at i(webpack://_N_E/./node_modules/@sentry/browser/esm/helpers.js:72:23)

Version:

"next-pwa": {
      "version": "3.1.5",
      "resolved": "https://registry.npmjs.org/next-pwa/-/next-pwa-3.1.5.tgz",
      "integrity": "*",
      "requires": {
        "clean-webpack-plugin": "^3.0.0",
        "globby": "^11.0.1",
        "workbox-webpack-plugin": "^5.1.4",
        "workbox-window": "^5.1.4"
      }
    }

**Comment by soutarm** [comment]
We're seeing this error a lot on prod mostly from Chrome on iOS

**Comment by Cherchercher** [comment]
> We're seeing this error a lot on prod mostly from Chrome on iOS

do you use a custom cache.js? just curious, still figuring out the bug

**Comment by KognitivnayaBuena** [comment]
same bug with custom cache.js config

**Comment by shadowwalker** [comment]
@Cherchercher @KognitivnayaBuena @soutarm How do I reproduce the error?

**Comment by darren-charterindex** [comment]
I'm seeing this issue on Safari 14 on MacOS 10.15.7. Everything is default.

**Comment by AnandChowdhary** [comment]
We are also seeing this on production on iOS Safari.
