### ISSUE TITLE
Next.js environmental variables not available in custom worker script

### ISSUE THREAD

**Issue by claudijo** [shadowwalker/next-pwa#165]
# Summary

Looking for a way to access Next.js environmental variables (as described here https://nextjs.org/docs/basic-features/environment-variables) in custom worker script. Currently environmental variables in a dot env file in a Next.js project will not be available in a custom worker script.

# How To Reproduce

1. Set up a Next.js project with the PWA-plugin. 
2. Include `.env.local` file in your Next.js project with some environmental variables, eg. `NEXT_PUBLIC_BASE_URL = http://localhost:8888`
2. Create a custom worker script in `worker/index.js` and try to access environmental variable eg `console.log(process.env.NEXT_PUBLIC_BASE_URL)`
3. Notice that the console output for the environmental variable will be `undefined`.

# Expected Behaviors

Expected output from steps described above would be to get `http://localhost:8888` as console output.

**Comment by sambecker** [comment]
Hitting a wall here too.

Would love to know if there's any way to put `/public/service-worker.js` through the typical `webpack`/`nextjs` build process, i.e., environment variables, TypeScript, etc.

At a minimum, would be nice not to need to commit environment variables to source control alongside service worker logic.

**Comment by shadowwalker** [comment]
This might be doable, I will work on this.
