### ISSUE TITLE
Error while building the example "cache-on-front-end-nav"

### ISSUE THREAD

**Issue by aspirin-vd** [shadowwalker/next-pwa#167]
![image](https://user-images.githubusercontent.com/23408234/108626683-7f856e00-7462-11eb-97da-72b45c4557fd.png)

  "dependencies": {
    "next": "^10.0.0",
    "next-pwa": "^5.0.5",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "webpack": "^4.41.5"
  }

The error disappears when you remove the next-pwa package.

node v14.14.0
npm 6.14.8

**Comment by shadowwalker** [comment]
I finally got something working, please try `next-pwa 5.1.3`
