### ISSUE TITLE
Custom worker not working_ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by arso1er** [shadowwalker/next-pwa#173]
Hi,

I've added your package to my nextjs project. I then created an index.js file in a worker folder, but when I build and start my app, I get this error in the browser's console: **ReferenceError: regeneratorRuntime is not defined**. These are the versions of next and react I'm using:
```
next": "9.5.5",
"next-pwa": "^5.0.5",
"react": "^16.13.1",
"react-dom": "^16.13.1"
```
Could you take a lot and help me solve this issue?

Thanks.

**Comment by shadowwalker** [comment]
You might need to consider upgrade both `next.js` and `next-pwa` to latest version to fix the problem.

**Comment by arso1er** [comment]
Thanks. That did the trick.
