### ISSUE TITLE
Using 'RangeRequestsPlugin'

### ISSUE THREAD

**Issue by g-farrow** [shadowwalker/next-pwa#174]
My PWA involves downloading mp3 files and having the Service Worker cache them for use in offline mode. In most browser this works just fine - the browsers can access the mp3 files and can access the metadata, including the "duration".

However, in Safari the metadata is unavailable. The app can't display "duration" or "currentTime". As I understand it, Safari works differently from other apps when making requests for this type of file. It initially makes a Range Request (which is where it gets the metadata from), followed by a second request for the file content.

I think that I can get the desired behaviour by using the [RangeRequestsPlugin](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-range-requests.RangeRequestsPlugin). My problem is, I have no idea how to use that plugin while using `next-pwa`. Is it possible to select Workbox plugins using the `next-pwa` library? If so, can someone share an example and some instructions please?

**Comment by shadowwalker** [comment]
Would you be able to create a minimal use case repo? I might be able to help with that.

**Comment by g-farrow** [comment]
hey @shadowwalker thanks for offering to help. I created a simple app in [this repo](https://github.com/g-farrow/next-pwa-demo-app) to demonstrate the problem.

The behaviour I see is in Safari (even on desktop version) and I see the audio behave as if it is a live stream:
![image](https://user-images.githubusercontent.com/22233709/110485750-e0a87500-80e3-11eb-862e-a2b5879bfc03.png) because the metadata has not been properly fetched in the range request:
![image](https://user-images.githubusercontent.com/22233709/110486015-22d1b680-80e4-11eb-9ac7-755ac5aa2097.png)

In other browsers, such as Chrome, I see this (working correctly):
![image](https://user-images.githubusercontent.com/22233709/110486210-59a7cc80-80e4-11eb-8be4-ef931d5f6845.png)
and this:
![image](https://user-images.githubusercontent.com/22233709/110486316-717f5080-80e4-11eb-923b-a17c25b84927.png)

I'd really like to avoid having to create a custom Service Worker, so if you can help me to configure my PWA to handle these Range Requests, that would be great. If the only way to get this to work is to use a custom Service Worker, then any help understanding how to configure that would be great too.

**Comment by g-farrow** [comment]
hey @shadowwalker I think I've got this resolved, by using a custom service worker:

```javascript
import { skipWaiting, clientsClaim } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import { RangeRequestsPlugin } from 'workbox-range-requests'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import {
  registerRoute,
  setDefaultHandler,
  setCatchHandler
} from 'workbox-routing'
import {
  matchPrecache,
  precacheAndRoute,
  cleanupOutdatedCaches
} from 'workbox-precaching'

skipWaiting()
clientsClaim()

const WB_MANIFEST = self.__WB_MANIFEST
WB_MANIFEST.push({
  url: '/fallback',
  revision: '1234567890'
})

precacheAndRoute(WB_MANIFEST)

cleanupOutdatedCaches()
registerRoute(
  '/',
  new StaleWhileRevalidate({
    cacheName: 'start-url',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 1,
        maxAgeSeconds: 24 * 60 * 60,
        purgeOnQuotaError: !0
      })
    ]
  }),
  'GET'
)
registerRoute(
  /.*\.(?:jpg|jpeg|gif|png|svg|ico|webp)\?.*/i,
  new CacheFirst({
    cacheName: 'image',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60,
        purgeOnQuotaError: !0
      })
    ]
  }),
  'GET'
)
registerRoute(
  /.*\.(?:mp3|wav|ogg)\?.*/i,
  new CacheFirst({
    cacheName: 'audio',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
        purgeOnQuotaError: !0
      }),
      new RangeRequestsPlugin()
    ]
  }),
  'GET'
)
registerRoute(
  /.*/i,
  new StaleWhileRevalidate({
    cacheName: 'others',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
        purgeOnQuotaError: !0
      })
    ]
  }),
  'GET'
)

setDefaultHandler(new StaleWhileRevalidate())

setCatchHandler(({ event }) => {
  switch (event.request.destination) {
    case 'document':
      return matchPrecache('/fallback')
    default:
      return Response.error()
  }
})
```

Providing code in case anyone in future needs this solution.
