### ISSUE TITLE
__WB_DISABLE_DEV_LOGS not working

### ISSUE THREAD

**Issue by matheusqro** [shadowwalker/next-pwa#179]
# Summary
I want to disable the workbox log in development mode.
Even putting it as true, it still keeps showing up.

# How To Reproduce

1. Create folder "worker"
2. Create file "index.js"
3. Add "self.__WB_DISABLE_DEV_LOGS = true;"

# Expected Behaviors
I need the debug to be removed by adding true to __WB_DISABLE_DEV_LOGS

# Screenshots
![Screenshot_6](https://user-images.githubusercontent.com/39939428/111941802-a1e5c800-8ab0-11eb-8ebe-da97471884d9.png)

**Comment by xkelxmc** [comment]
Use disable for development
```
module.exports = withPWA({
    future: {
        webpack5: true
    },
    pwa: {
        disable: process.env.NODE_ENV === 'development',
        dest: 'public'
    }
})
```

**Comment by shadowwalker** [comment]
Can you first try `next-pwa 5.1.3`?

**Comment by EpicHigh** [comment]
I am encountering this issue too. I am using `next-pwa 5.1.3`.

**Comment by shadowwalker** [comment]
Try another way, set in your pwa config: `mode: 'production'`

**Comment by EpicHigh** [comment]
Thank you for your response. It's not working.

Here's my PWA config.
```
pwa: {
          disable: process.env.NODE_ENV === 'development',
          register: true,
          dest: 'public',
          runtimeCaching,
          mode: 'production'
        }
```

**Comment by shadowwalker** [comment]
I could reproduce this error. But it works perfectly after I clean everything up and rebuild under development mode. I think you can fix this too.

1. Exit development process if you are still running `yarn dev` or `next`
2. Create custom worker `worker/index.js` or `worker/index.ts` and add `self.__WB_DISABLE_DEV_LOGS = true` on the top of the file.
3. Remove `.next` folder
4. Run `yarn dev`
5. Open browser and navigate to your app and under `Application` tab in development tools, click 'Clear site data', then right click the refresh button and click 'Empty Cache and Hard Reload'
6. Everything should work as expected now, workbox does not produce logs to your console now.
 
![image](https://user-images.githubusercontent.com/9603375/113499600-334f3400-94cc-11eb-9084-83e785f246a0.png)

@EpicHigh tips for your pwa config, you should update your config to this: (minimal is enough)

```javascript
pwa: {
  dest: 'public'
}
```

**Comment by EpicHigh** [comment]
Wow, I appreciate that. Thank you for your hekp. It's work as expected.

**Comment by matheusqro** [comment]
@shadowwalker Thanks :)
