### ISSUE TITLE
Custorm worker don't work

### ISSUE THREAD

**Issue by xkelxmc** [shadowwalker/next-pwa#185]
# Summary

Crush on build with any webpack and have custom worker

# How To Reproduce

1. Install example with custom worker or custom worker ts (repriduce in my project too)
2. run yarn install
3. run yarn build

# Screenshots

![image](https://user-images.githubusercontent.com/1748318/113468893-d6169c80-9451-11eb-9a6d-5cbae0c10e2d.png)

![image](https://user-images.githubusercontent.com/1748318/113468911-efb7e400-9451-11eb-8d18-76e0b7b5651d.png)

**Comment by xkelxmc** [comment]
And in my project 
![image](https://user-images.githubusercontent.com/1748318/113468936-2130af80-9452-11eb-9300-41d57dd2a5b3.png)

**Comment by shadowwalker** [comment]
I finally got something working, please try `next-pwa 5.1.3`

**Comment by xkelxmc** [comment]
> I finally got something working, please try `next-pwa 5.1.3`

Yeah! Its work! Good job!
