### ISSUE TITLE
How can I unregister a service worker to disable a PWA?

### ISSUE THREAD

**Issue by jahirfiquitiva** [shadowwalker/next-pwa#191]

**Comment by shadowwalker** [comment]
Is this what you are looking for? In `next.config.js`, set

```javascript
pwa: {
  register: false
}
```

**Comment by jahirfiquitiva** [comment]
does this unregister an already registered app? or does it just not auto register the app? 🤔

**Comment by shadowwalker** [comment]
This is not auto register the app in the beginning.

If you want to unregister the service worker in runtime, you can try this: https://stackoverflow.com/a/33705250

**Comment by jahirfiquitiva** [comment]
oh, but where should I put that in my next app? 😬
