### ISSUE TITLE
dynamicStartUrl caused chrome to goes offline after first redirection

### ISSUE THREAD

**Issue by panjiesw** [shadowwalker/next-pwa#194]
# Summary

When setting `dynamicStartUrl: true` option, the new installability check in Chrome 89 disappeared, visitting `start-url` got redirected correctly as intended. But when I tried to visit the `start-url` again after the first redirection, it won't open the page and chrome's offline page was shown instead.

Chrome's DevTool also show this warning

```
The FetchEvent for "http://localhost:3000/" resulted in a network error response: a redirected response was used for a request whose redirect mode is not "follow".
Promise.then (async)
(anonymous) @ Router.js:58
```

# How To Reproduce

I've created a minimal repro here: https://github.com/panjiesw/pwa-repro with this `next.js.config`

```js
const withPWA = require('next-pwa');

module.exports = withPWA({
  pwa: {
    dest: 'public',
    dynamicStartUrl: true,
  },
});
```

1. Clone the repo above
2. Run `yarn dev` (or `yarn build` then `yarn start`)
3. Go to http://localhost:3000
4. You'll be redirected to http://localhost:3000/login
5. Re-visit http://localhost:3000 again
6. Chrome's offline page will be shown

# Expected Behaviors

Users should still be able to re-visit `start-url` after they got redirected when using `dynamicStartUrl` instead of shown Chrome's offline page.

# Screenshots

Chrome DevTool warning:

![2021-04-08-222232_4480x1440_scrot](https://user-images.githubusercontent.com/1451848/114055021-9240ee80-98ba-11eb-9c64-02ca9fe6a275.png)

Chrome offline page:

![2021-04-08-222342_4480x1440_scrot](https://user-images.githubusercontent.com/1451848/114055055-9a009300-98ba-11eb-81dc-3b3cd1a7c031.png)

# Additional Context

My PWA require a redirection from `start-url` (`/`) to a login page if not authenticated (handled server side in Next.js). Before, the PWA got Chrome's warning that it won't be installable in Chrome 93 onwards, so I'm trying `dynamicStartUrl` feature in `next-pwa`.

**Comment by panjiesw** [comment]
**Update**: Seems like it's also causing error in Firefox

![pwa_ff_console](https://user-images.githubusercontent.com/1451848/114056392-cff24700-98bb-11eb-8d40-7ba21932e634.png)

![pwa_ff_error](https://user-images.githubusercontent.com/1451848/114056408-d4b6fb00-98bb-11eb-8e51-f89c9438025d.png)

**Update Environment**:
- Node.js `v14.5.4`
- Next.js `v10.1.3`
- next-pwa `v5.2.3`

**Comment by panjiesw** [comment]
**Update**: found a response for your workaround here: https://github.com/GoogleChrome/workbox/issues/2749#issuecomment-813489953, do you suggest to not enable `dynamicStartUrl` for now? Since the offline check likely will get improvement in Chrome anyway

**Comment by tatethurston** [comment]
Also encountering this issue on iOS Safari 12-14.x with next-pwa `v5.1.4`

**Comment by tatethurston** [comment]
Also encountering this issue on iOS Safari 12-14.x with next-pwa `v5.1.4`. Looks like `dynamicStartUrl` became the default in https://github.com/shadowwalker/next-pwa/commit/c6416215bcdec6cc49540259f47863f14ea8f39d

**Comment by shadowwalker** [comment]
Try version `5.2.4` and config this option:
https://github.com/shadowwalker/next-pwa/blob/a15c9f612787edef125426a049b841ecc12b26c9/examples/cookie/next.config.js#L7

**Comment by panjiesw** [comment]
@shadowwalker thanks using `dynamicStartUrlRedirect` works! But seems like there is `console.log` statement here https://github.com/shadowwalker/next-pwa/blob/f9955c26dbd092e262f457a20bc9a2f46295fd03/register.js#L5 

Is that a left over from development or an intended one? It's shown even in production build.

**Comment by shadowwalker** [comment]
Version `5.2.7` should fix this problem.

**Comment by panjiesw** [comment]
Sorry for not getting back sooner. I've confirmed that the issue has been fixed using latest version, thanks @shadowwalker!
