### ISSUE TITLE
scope not allowed

### ISSUE THREAD

**Issue by kush-agra** [shadowwalker/next-pwa#195]
# Summary

next-pwa returns error `Please check your GenerateSW plugin configuration: "scope" is not allowed` during build

works in v5.0.6 gives error after that, can be reproduced in 5.2.5

# How To Reproduce

1. Add a scope in next.config.js
2. Run next build

# Expected Behaviors
Build to finish successfully and sw generated with the specified scope 

# Screenshots

![Screenshot 2021-04-09 at 2 45 52 PM](https://user-images.githubusercontent.com/8018852/114158437-4b96d700-9942-11eb-932c-a7d9cf61b06a.png)

**Comment by shadowwalker** [comment]
Version `5.2.7` should fix this problem.
