### ISSUE TITLE
terser-webpack-plugin with Next.js + Webpack 4

### ISSUE THREAD

**Issue by fatihtelis** [shadowwalker/next-pwa#198]
# Summary

I'm using Next.js with Webpack 4 and when I add a fallback page to pages/_offline, terser-webpack-plugin gives the error below:

TypeError: Cannot read property **'javascript' of undefined**
    at /Users/xxxxxxxxx/node_modules/**terser-webpack-plugin**/dist/index.js:572:38

I searched for the issue and terser-webpack-plugin@5+ is for Webpack 5 and is not compatible with Webpack 4.

# How To Reproduce

1. Use next-pwa@5.2.9 which has a dependency for  terser-webpack-plugin: "^5.1.1" (Only compatible with Webpack 5)
2. Use next.js with Webpack 4
3. Add a fallback page to pages/_offline.js
4. Get error while building the app.

**Comment by shadowwalker** [comment]
Unfortunately this is a unsolvable problem, if I don't add `terser-webpack-plugin` as dependency in `next-pwa`. Other folks will see another build error.
Can you try to use `{future: webpack5}` in your project or try install the lower version of `terser-webpack-plugin` by `yarn install terser-webpack-plugin@4.2.3` to mitigate the issue you have encountered?

**Comment by fatihtelis** [comment]
I upgraded to Webpack 5. It is working properly now. Thanks for the reply @shadowwalker.

**Comment by quick007** [comment]
You now just use `webpack5: true,` in the nextjs config
