### ISSUE TITLE
Support typescript form src folder

### ISSUE THREAD

**Issue by HofmannZ** [shadowwalker/next-pwa#204]
Nextjs support projects with the `pages` directory under `src/` currently `next-pwa` does not detect a `_offline` page on the  `src/pages/_offline.tsx` path.

Additionaly custom workers under  the `src/` directory alre also not picked up.

**Comment by shadowwalker** [comment]
Should be fixed in `5.2.14`

**Comment by HofmannZ** [comment]
Thanks! That was quick 😄
