### ISSUE TITLE
After SW is installed, start_url is inaccessible

### ISSUE THREAD

**Issue by bduff9** [shadowwalker/next-pwa#205]
> @bduff9 When the user first visit your `start_url` does it return some page or HTML document? even through redirect will work.
> 
> I will be working on a new feature to fallback to `_error` page or configurable page.

Yes, my start_url is the index page (`/`).  I have a server-side 301 redirect on this page to `/auth/login` when not signed in.  When I run this in Chrome, I am getting a message that this cannot be installed.  This message seems to go away after sign-in, which is why I am thinking this new check will prevent my app from being installed.

```
The FetchEvent for "https://....com/" resulted in a network error response: an "opaqueredirect" type response was used for a request whose redirect mode is not "manual".
Uncaught (in promise) TypeError: Failed to fetch
Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
```

_Originally posted by @bduff9 in https://github.com/shadowwalker/next-pwa/issues/177#issuecomment-812945123_

Following up on this issue from the previous ticket, my fetch error is now gone.  But, if I visit the application and don't sign in when I go back to the URL, I get an error that `This site can't be reached`.  It's still accessible though from new browsers or after I manually clear the sw.

**Comment by shadowwalker** [comment]
Which version are you using currently?

**Comment by bduff9** [comment]
5.2.9

**Comment by shadowwalker** [comment]
Do you happen to have a deployed url I could help you troubleshoot?

**Comment by bduff9** [comment]
Yes I do, but I'd prefer to share it privately with you.  How can I do so?

**Comment by shadowwalker** [comment]
Send me an email or LinkedIn message which you could find on my GitHub profile.

**Comment by bduff9** [comment]
Great, thank you.  Just sent you an email

**Comment by bduff9** [comment]
Seems issue went away.  Either was caused by an older version of next-pwa that was not fully cleared out until recent or by recent Chrome changes.  Either way, I cannot reproduce anymore so closing this for now.  Thanks for your assistance @shadowwalker !
