### ISSUE TITLE
Next-pwa doesn't work with Sentry/nextjs plugin

### ISSUE THREAD

**Issue by abordeau** [shadowwalker/next-pwa#213]
# Summary

I tried to use next-pwa with the sentry integration but the service-worker is not register in this case.
 
# Versions

- `next-pwa`: 3.1.0
- `next`:10.2.0
- `@sentry/nextjs`: ^6.3.6

# How To Reproduce

1. Clone [this repo](https://github.com/abordeau/nextjs-pwa-sentry-test)
2. Install the app with `yarn install` and run it with `yarn dev`
3. Open the navigator on http://localhost:3000/
4. Check if a service worker is registered in the chrome dev tools

# Expected Behaviors

The `sw.js` file and the `workbox.js` are created in the public folder but they are not registered by the browser

This is the next.config.js file I used :

```
const withPWA = require('next-pwa')
const runtimeCaching = require('next-pwa/cache')
const { withSentryConfig } = require('@sentry/nextjs')

const moduleExports = withPWA({
  pwa: {
    dest: 'public',
    runtimeCaching,
  },
})

const SentryWebpackPluginOptions = {
  // Additional config options for the Sentry Webpack plugin. Keep in mind that
  // the following options are set automatically, and overriding them is not
  // recommended:
  //   release, url, org, project, authToken, configFile, stripPrefix,
  //   urlPrefix, include, ignore
  // For all available options, see:
  // https://github.com/getsentry/sentry-webpack-plugin#options.
}

// With this config, the service worker  is not registered by the browser
module.exports = withSentryConfig(moduleExports, SentryWebpackPluginOptions)

// This config works
// module.exports = moduleExports

```

**Comment by wonderlandpark** [comment]
This happens to me too.

**Comment by nihalanisumit** [comment]
I'm having the same issue :/

although my next.config.js file looks a lil different
```
const withPlugins = require('next-compose-plugins')
const { withSentryConfig } = require('@sentry/nextjs')
const withPWA = require('next-pwa')
const runtimeCaching = require('next-pwa/cache')
const withSvgr = require('next-svgr')

const sentryWebpackPluginOptions = {
  // For all available options, see:
  // https://github.com/getsentry/sentry-webpack-plugin#options.
}
const PWAPluginOptions = {
  pwa: {
    dest: 'public',
    runtimeCaching,
  },
}

module.exports = withPlugins([withSvgr, [withPWA, PWAPluginOptions], [withSentryConfig, sentryWebpackPluginOptions]])

```

**Comment by abordeau** [comment]
I also tried with **withPlugins** and yes, same error.

**Comment by nihalanisumit** [comment]
@abordeau did you try any other solution or any other library?

**Comment by abordeau** [comment]
I close this issue since the bug was resolve by the Sentry teams (https://github.com/getsentry/sentry-javascript/issues/3538)
Thanks anyway 👌🏼

**Comment by mburri** [comment]
Actually, the Issue was reopened again: https://github.com/getsentry/sentry-javascript/issues/3538#issuecomment-856896363
