### ISSUE TITLE
Offline example not working

### ISSUE THREAD

**Issue by ivandotv** [shadowwalker/next-pwa#219]
# Summary
Looking at the offline example 2. It appears that it's not working.
https://github.com/shadowwalker/next-pwa/blob/master/examples/offline-fallback-v2/README.md
# Versions

- `next-pwa`:  5.2.21
- `next`: 10.2.3

# How To Reproduce

1. start server
2. open website
3. open dev tools - > application -> service worker -> switch "offline"
4. reload page

Browser offline page is shown (dinosaur)

# Expected Behaviors
See fallback image.

**Comment by egluhbegovic** [comment]
I am having the same issue when testing on mobile, iOS Safari, and Android Chrome.

**Comment by shadowwalker** [comment]
Please use following to see it's working by starting production sever, service worker is not fully functioning by default in dev server. (This is by design)

```
yarn build
yarn start
```
