### ISSUE TITLE
Excluding some pages based on urls or patterns.

### ISSUE THREAD

**Issue by efleurine** [shadowwalker/next-pwa#22]
Hi thanks for this great package.

I have a quick question. Assuming I want to exclude some pages from being cached. Like let's say `/dashboard` and/or `/dashboard/*` is that possible?.

If yes, could you point me in the right direction. Thank you. I am new to pwa and offline all.

Thanks in advance.

**Comment by harshzalavadiya** [comment]
I was also wondering the same that instead of just `public` folder excludes is it possible to exclude some url's

because I have nginx reverse proxying nextjs application and have multiple microservices mapped in a context being cached by service worker that I don't need

**Comment by shadowwalker** [comment]
@efleurine and @harshzalavadiya , absolutely you can achieve this by specify `runtimeCaching` in your pwa config. You can provide runtime cache configuration completely by your own, you provide a function to modify default runtime cache. For the structure of this configuration, I recommend to take a closer look at [cache.js](https://github.com/shadowwalker/next-pwa/blob/master/cache.js)

Example

## 1st Way

``` javascript
...
  pwa: {
    runtimeCaching: [
      {
        urlPattern: /.*/i,
        handler: 'StaleWhileRevalidate',
        options: {
          cacheName: 'others',
          expiration: {
          maxEntries: 16,
          maxAgeSeconds: 24 * 60 * 60 // 24 hours
        }
      }
    }, { ... }]
  }
...
```

## 2nd Way
``` javascript
  pwa: {
    runtimeCaching: (defaultCache) => {
      // do some modification on defaultCache
      return defaultCache
    }
  }
```

**Comment by harshzalavadiya** [comment]
@shadowwalker Thanks for quick response also I found [this link](https://developers.google.com/web/tools/workbox/reference-docs/v2/module-workbox-runtime-caching) showing workbox documentation for cache options

**Comment by shadowwalker** [comment]
https://github.com/shadowwalker/next-pwa/blob/7c83f896ce0161dbfe7ecd2afb6b52526137c798/index.js#L180

It should work as long as return is an array.

**Comment by sospedra** [comment]
Hey @shadowwalker it doesn't work, very weird 😕 
When a function is provided somehow an array is not passed. I did some debugging and everything looks fine. And it looks like an array is getting passed to Workbox. But it triggers this error:

![Kapture 2020-04-03 at 11 34 30](https://user-images.githubusercontent.com/3116899/78346418-51bfde00-759f-11ea-8870-24c6595e0962.gif)

If a literal array is provied, instead, it works wihout hassle 🤔

**Comment by harshzalavadiya** [comment]
@sospedra, I did the same thing back then to resolve this issue, since I didn't needed fontawesone and google fonts

**Comment by shadowwalker** [comment]
I've removed the support for the second method, as I could not figure out what's wrong.
