### ISSUE TITLE
manifestTransform for dynamic routes misses catch all routes

### ISSUE THREAD

**Issue by Pikachews** [shadowwalker/next-pwa#223]
# Summary

The following snippet seems to be intended to transform the square brackets (`[`/`]`) in the file names into the respective HTML entities (`%5B`/`%5D`). However, it misses the case of catch-all routes due to trying to also matching the `/` preceding a `[`.

https://github.com/shadowwalker/next-pwa/blob/334c5decd24abf539bc255c01231d0ccd957e61f/index.js#L219-L223

This ends up transforming `/path/to/file/[[...slug]]-hash.js` to `/path/to/file/%5B[...slug%5D%5D-hash.js`, which does not end up matching the request (`/path/to/file/%5B%5B...slug%5D%5D-hash.js`).

Not sure if there are other effects to this, but removing the forward slash from the match seems to fix the problem.

# Versions

- `next-pwa`: 5.2.21
- `next`: 10.2.3

# Expected Behaviors

The script should be properly cached the at installation and not requested again when the page requiring it is loaded.

# Screenshots

File in the `workbox-precache` after PWA caches at installation:
![image](https://user-images.githubusercontent.com/5668416/121797746-170bf980-cbd7-11eb-8cbb-c3e1a13b264c.png)

File in the `static-js-assets` cache after being requested + cached:
![image](https://user-images.githubusercontent.com/5668416/121797750-212df800-cbd7-11eb-8b59-a605cbdd2f50.png)

**Comment by shadowwalker** [comment]
Fixed, update to latest version
