### ISSUE TITLE
[Question] Caching of external dependencies ? 

### ISSUE THREAD

**Issue by leobenkel** [shadowwalker/next-pwa#227]
Hello,

Thank you so much for this project. Such a good gain of time. I had to configure the service-worker once and it was a pain. 

I have a quick questions. I am relying on `fonts.googleapis.com` to fetch fonts and more importantly the `material icons` one. Without it, the website looks weird with the name of the icon rendered instead of the icons themselves. 

I have 
```
@import url("https://fonts.googleapis.com/css?family=Open+Sans:300,400,500|Material+Icons|Material+Icons+Outlined");
```
In my `global.scss` right now. 

In https://github.com/shadowwalker/next-pwa#available-options , I see that I can `exclude` resources, which I am using, would there be a way to specifically add external dependencies ? 

Thank you !

**Comment by shadowwalker** [comment]
For the url below
```
https://fonts.googleapis.com/css?family=Open+Sans:300,400,500|Material+Icons|Material+Icons+Outlined
```
Do you want to cache it or not?
Either way, you could customize your own runtimeCaching config.

**Comment by leobenkel** [comment]
I do want to cache it

**Comment by shadowwalker** [comment]
https://github.com/shadowwalker/next-pwa/blob/3f269c8c8e968777303d0c910e177a39c64d2f85/cache.js#L17-L26
This should already be cached using "StaleWhileRevalidate" strategy, if you would like to customize, copy the config from this file, modify it, then passing it to `runtimeCaching` config in `pwa` config section.

**Comment by leobenkel** [comment]
Thank you !
