### ISSUE TITLE
Next PWA Adding double `//` when using static imports in next/image

### ISSUE THREAD

**Issue by SimpleIndian** [shadowwalker/next-pwa#231]
# Summary

Next PWA Adding double `//` when using static imports in next/image
```bash
/_next//static/image/public/images/logo.0a2481ce618555d10030a7d5a6413bc1.svg
```
 import style:
```bash
import logo from 'public/images/logo.svg';`
```
on `jsconfig.json`:
```bash
"public/*": ["./public/*"],
```
# Versions

- `next-pwa`: 5.2.21
- `next`:11.0.1

# Expected Behaviors
only one `/` is needed and valid

**Comment by shadowwalker** [comment]
Should be fixed, upgrade to latest version.
