### ISSUE TITLE
Install PWA in Chrome for Android

### ISSUE THREAD

**Issue by Emiliano-Bucci** [shadowwalker/next-pwa#24]
Hi! This is more a doubt rather than a bug, and i was wondering if you could maybe help me. Currently i started to use this lib and i have no issues with it. I've also run audits inside Chrome regarding PWA and i have no errors at all; still, there's no message to install the PWA in Chrome for Android. Do you know what this could be? Is a normal behavior?

Thanks a lot!

**Comment by shadowwalker** [comment]
Could you specify android version, chrome version and phone model you are testing on? Have you try cleanup all local storage?

**Comment by Emiliano-Bucci** [comment]
Hi, thanks for the quick answer! :) Currently the issue was not the `localStorage` but an old service worker that was still active (in the past i used `next-offline` while i was doing some test but i didn't remember :D Sorry, for the bother, i'm closing this!

**Comment by Emiliano-Bucci** [comment]
Hi, sorry again but i believe the issue isn't gone at all. I've noticed few things:
- When developing, if i release (i use now), and don't remove the sw files created in dev, when the app is up i get a 404 because it can't find the `sw.map.js`

Second point is that, even clearing the `localStorage` and unregistering all service workers (connecting the phone to the pc) the popup to install the App don't appear. 

i have a Huawei P10 with Android 8 and Chrome version is 80.x

Thanks! :)

**Comment by shadowwalker** [comment]
@Emiliano-Bucci Please see my comments in issue 25
