### ISSUE TITLE
Blank page and failed requests

### ISSUE THREAD

**Issue by AlexTechNoir** [shadowwalker/next-pwa#240]
# Summary

I recently started to learn PWA, specifically Service Workers. Following the official docs I created **next.config.js**, copied the basic config code there and launched **npm run dev** (4 files were successfully generated in **public** folder). The browser shows blank page, console shows many failed requests. It happens in offline mode.

# Versions

- `next-pwa`: ^5.2.23
- `next`: ^11.0.1

# How To Reproduce

1. [create-next-app](https://nextjs.org/docs/getting-started#setup) and install next-pwa.
2. Create **next.config.js** and copy the code from [official example](https://github.com/shadowwalker/next-pwa#usage-without-custom-server-nextjs-9).
3. Launch the app with **npm run dev**.
4. Simulate offline mode in Chrome Dev Tools.
4. See error.

# Expected Behaviors

App should work offline.

# Screenshots

![0](https://user-images.githubusercontent.com/43852391/126319281-b5019ace-bbf9-4274-b23e-845f2fc84c1e.jpg)

![1](https://user-images.githubusercontent.com/43852391/126319290-e70f7690-f79c-4055-8a2b-8e0d98671fc2.jpg)

![2](https://user-images.githubusercontent.com/43852391/126319300-afe11118-df27-43e6-b9cf-e581572880f9.jpg)

**Comment by shadowwalker** [comment]
By default, PWA functionality is limited running in dev mode, this is by design. If you want to see offline working, try running in production mode with `next start`.
