### ISSUE TITLE
Involuntary reload when there is a change in network connectivity

### ISSUE THREAD

**Issue by myasul** [shadowwalker/next-pwa#244]
# Summary

First just want to say thank you for this awesome library that really helped us create a PWA app right off the bat!

Our application is an offline-first application. It uses redux to save state and also `next-pwa` to do PWA stuff. Whenever the app comes from being offline to online, it triggers a big refresh of the redux state tree and it works well. But when we upgrade `next-pwa` it changed behavior. Whenever it detects an internet connection it involuntarily refreshes the whole app which messes up the big redux state hydration.

I saw that the `register.js` has a listener that does it. 
The question is what is the significance of the reload?

```typescript
  window.addEventListener('online', () => {
    location.reload()
  })
```

# Versions

- `next-pwa`: 5.2.23
- `next`: 11.0.0

# How To Reproduce

1. Go offline via the Network tab in the developer tools
2. Go online again.

Link to minimal reproduce setup repository if any.

# Expected Behaviors

The app should not refresh regardless of the internet connection status.

**Comment by sanderkooger** [comment]
Hey @myasul 

Below a copy of my withPWA block in next.config.js 

```
 withPWA({
        pwa: {
          dest: 'public',
          disable: process.env.NODE_ENV === 'development',
          // mode: 'development', // enable verbose loggin in prod
          buildExcludes: [/chunks\/images\/.*$/], // Don't precache files under .next/static/chunks/images this improves next-optimized-images behaviour
          skipWaiting: true, // installs new SW when available withou a promt, we only need to send a reload request to user.
          reloadOnOnline: false // Prevents reloads on offline/online switch
        }
      })
``` 
the reloadOnOnline is where the magic happens.

**Comment by myasul** [comment]
@sanderkooger I just noticed this! Yes, it seems that it was fixed on the latest version! Will close it now!
