### ISSUE TITLE
Error when running build: 'cacheWillUpdate' property type must be object.

### ISSUE THREAD

**Issue by marlonmarcello** [shadowwalker/next-pwa#255]
# Summary
Getting an error when running `next run build`.

```
Failed to compile.

Please check your GenerateSW plugin configuration:
[WebpackGenerateSW.runtimeCaching.0.options.plugins.0.cacheWillUpdate] 'cacheWillUpdate' property type must be object.
```

# Versions

- `next-pwa`: ^5.2.24
- `next`: 11.0.1

**Comment by marlonmarcello** [comment]
```js
// next.config.js
module.exports = withPWA({
  pwa: {
    dest: "public",
    disable: process.env.NODE_ENV !== "production",
  },
  reactStrictMode: true,
  webpack5: false,
});
```

**Comment by marlonmarcello** [comment]
My bad. Wrong call during `getStaticProps`

**Comment by marlonmarcello** [comment]
If it's of any help. I am using SSR with api routes.

**Comment by enspiregaurav** [comment]
I also had similar issue , I downgraded to v5.1.0 and it worked.

**Comment by currybob** [comment]
i also having same issue..

**Comment by currybob** [comment]
> I also had similar issue , I downgraded to v5.1.0 and it worked.
i had also same issue, and it worked correctly for me

**Comment by currybob** [comment]
> > I also had similar issue , I downgraded to v5.1.0 and it worked.
> 
> i had also same issue, and it worked correctly for me . thanks for @enspiregaurav

**Comment by RobinGiel** [comment]
I tried downgrading and I'm having the same issue

**Comment by rtritto** [comment]
This bug should be resolved when version 6.2.1 of `workbox-build` (dependency of `workbox-webpack-plugin` which is used by `next-pwa`) is released.
After that, remove and resinstall `next-pwa`.

**Comment by quypb** [comment]
Thanks @rtritto, It works now.

**Comment by shadowwalker** [comment]
Should be fixed with latest release of `next-pwa`. If not, please re-open this issue
