### ISSUE TITLE
Error CORS when import arc.io script.

### ISSUE THREAD

**Issue by meotimdihia** [shadowwalker/next-pwa#263]
# Summary
I am getting this error when import arc.io service worker with `next-pwa`

> Access to fetch at 'https://tracker.arc.io/' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I tried to import with simple sw.js file and it works: 
```js
self.importScripts('https://arc.io/arc-sw-core.js')
self.skipWaiting()
```

# Versions

- `next-pwa`: 5.2.24
- `next`: 10.0.1

# How To Reproduce
in `next.config.js`:
```
pwa: {
    importScripts: ["https://arc.io/arc-sw-core.js"]
}
```
# Expected Behaviors
The error should not happen.
P/S: I stopped use arc io...

**Comment by shadowwalker** [comment]
Due to security concerns, you should not import scripts inside a service that's sourced from external website. Otherwise you are open a worm hole for attackers. Just have the scripts copied and host it yourself.
