### ISSUE TITLE
ReferenceError: pageExtensions is not defined

### ISSUE THREAD

**Issue by rafiandria23** [shadowwalker/next-pwa#265]
# Summary

As mentioned in the title, I got pageExtensions undefined, when I downgraded to version 5.2.24, it went back to work just fine.

# Versions

- `next-pwa`: ^5.3.0
- `next`: 11.1.0

# How To Reproduce

1. Run `yarn add next-pwa`
2. Run `yarn dev`
3. You'll see the error, it immediately exits with the message (in screenshot).

It's a private repo, so all I can give is the screenshot.

# Expected Behaviors

The `next dev` script should keep running without exiting.

# Screenshots

Here's my next.config.js

<img width="389" alt="Screen Shot 2021-08-16 at 1 14 33 PM" src="https://user-images.githubusercontent.com/53303941/129519177-c42dbf12-1ca7-45b7-99e8-0b03f4ebd456.png">

Here's the error screenshot

<img width="1069" alt="Screen Shot 2021-08-16 at 1 18 16 PM" src="https://user-images.githubusercontent.com/53303941/129520000-862aa50e-a2a2-4d40-801b-7a3011f065b7.png">

**Comment by zhanghecool** [comment]
I have the same error
![企业微信20210816-145741](https://user-images.githubusercontent.com/7930156/129523523-f5da797e-90bf-411b-878e-90679c6d291a.png)

**Comment by anshulagx** [comment]
Same for me as well

**Comment by anshulagx** [comment]
This is a problem with the latest update.
Switching back to  "next-pwa": "5.2.24" in package.json works for me, for now.

**Comment by Vicnovais** [comment]
I have the same issue! Apparently the function getFallbackEnvs is missing "pageExtensions" argument

![image](https://user-images.githubusercontent.com/7889190/129585069-07bdbacb-223a-4f51-a94f-7c8461c80771.png)

**Comment by arafatamim** [comment]
> Apparently the function getFallbackEnvs is missing "pageExtensions" argument
High time for a project like this to start using a linter or even a transpiler like TypeScript to avoid these silly human errors, don't you think?

**Comment by shadowwalker** [comment]
Fixed in `5.3.1`

**Comment by rafiandria23** [comment]
It works just fine now, thank you @shadowwalker
