### ISSUE TITLE
How to deal with not found assets for new deploying If we set dynamicStartUrl false. 

### ISSUE THREAD

**Issue by meotimdihia** [shadowwalker/next-pwa#267]
# Summary

When a new deploying and CDN cleared assets like JS, CSS.  And the service worker still serves the old homepage version.

This is a screenshot: 
![xk2jWtb 1](https://user-images.githubusercontent.com/300961/130116564-f8fdcd1b-2377-4924-afe6-664024210bca.png)

# Versions
- `next-pwa`: 5.2.24
- `next`: 11.1.0

Do we have a way to force service workers to delete the old version of the start page?

**Comment by meotimdihia** [comment]
I think to change the path "/" to StaleWhileRevalidate is required for this problem?

{
  urlPattern: "/",
  handler: "StaleWhileRevalidate",
  options: {
    cacheName: "start-url",
    expiration: {
      maxEntries: 4,
      maxAgeSeconds: 1
    }
  }
}

**Comment by meotimdihia** [comment]
@shadowwalker I wonder why with default settings dynamicStartUrl: true.
When the service worker was installed. The path "/" behavior is not the same as without a service worker.
For example, it always has to refetching home page:
![msedge_2021-08-20_21-28-46](https://user-images.githubusercontent.com/300961/130248930-17cf28d3-ae0e-47f3-957f-ea17f392a9fd.png)

It is different from the default next.js behavior. This is example: https://stackblitz.com/edit/github-dn74e4?file=pages/about.js

I think we shouldn't change this behavior when it works well for everyone.

**Comment by shadowwalker** [comment]
Hi, @meotimdihia !

For the doc

```
dynamicStartUrl - if your start url returns different HTML document under different state (such as logged in vs. not logged in), this should be set to true.
default: true
recommend: set to false if your start url always returns same HTML document, then start url will be precached, this will help to speed up first load.
```

This was there to solve a particular problem with a common pattern. When a user sign in the web app, cookies is set and redirect back to home page. With SSR, server received the cookie and determined the user is signed in and render the HTML on server and send back a different HTML than the cached one.

The option set to true solved the problem that user get confused after sign in and still see old HTML.

You can play this use case using the https://github.com/shadowwalker/next-pwa/tree/master/examples/cookie example, just try turning this option off and see how things goes.

**Comment by meotimdihia** [comment]
@shadowwalker: But the problem "re-fetch" doesn't happen with other static pages but the static homepage. Its behavior is different from Next.js without PWA.

**Comment by shadowwalker** [comment]
I think what you have mentioned coming from here:

https://github.com/shadowwalker/next-pwa/blob/54bbba6631f5a65cd51ab1671fadade319e652f2/register.js#L51-L56

And start url is defined here:

https://github.com/shadowwalker/next-pwa/blob/54bbba6631f5a65cd51ab1671fadade319e652f2/index.js#L80

I'm not sure if I should change the logic here, as it was meant to solve the particular problem, and maintain the usability by default. Do you have any good suggestions how this should be implemented without breaking anyone?

**Comment by meotimdihia** [comment]
@shadowwalker Sorry, I don't really understand exactly how workbox works 😅. 
But I think this problem is important.  But people just don't know it.
For example, sites like Facebook, Twitter. The users always click to view photos or comments then go back to the **homepage** multiple times. 
Currently, go back to the homepage add an extra request, the site will be slow.

**Comment by meotimdihia** [comment]
I think this is a serious problem. The config `dynamicStartUrl: false` could break the site.

```js
const cache = require("next-pwa/cache")

cache.push({
  urlPattern: "/",
  handler: "StaleWhileRevalidate",
  options: {
    cacheName: "start-url", // CHANGE THIS TO start-url
    expiration: {
      maxEntries: 10,
      maxAgeSeconds: 36400
    }
  }
})

  pwa: {
    dest: "public",
    disable: process.env.NODE_ENV !== 'production',
    // register: false,
    // swSrc: 'service-worker.js',
    buildExcludes: [/static\/media\/.*\.svg$/],
    // runtimeCaching: cache,
    dynamicStartUrl : false,
    skipWaiting: true
  }
```

When I change the homepage, and it takes forever for the browser with an existing worker to update the new version.
I think StaleWhileRevalidate will update the cache after the first request?

**Comment by meotimdihia** [comment]
We can reproduce the problem by these steps:

1. build the site : `yarn build && yarn start` with `{dynamicStartUrl: false}`
2. And go to the local site. 
4. Modify the homepage for visible.
3. And build it again with `{disable: true}`
5. You can't see the change in step 4

**Comment by meotimdihia** [comment]
I solved this problem by updating:
` __PWA_START_URL__: dynamicStartUrl ? '${basePath}' : undefined,`  to  `__PWA_START_URL: undefined`
at line: https://github.com/shadowwalker/next-pwa/blob/67e4d58b31d52180b5eb603cab839705851a59d4/index.js#L80

with PWA config: 
```js
  pwa: {
    runtimeCaching: [],
    dynamicStartUrl : true,
  }
  ```

**Comment by meotimdihia** [comment]
I close this issue since the patch solved it.
