### ISSUE TITLE
Broken in dev mode

### ISSUE THREAD

**Issue by Hainesy** [shadowwalker/next-pwa#28]
When running in dev mode:

![image](https://user-images.githubusercontent.com/520883/78889631-efae1f80-7a5b-11ea-91bb-7497aa901830.png)

It eventually gets stuck requesting resources.

**Comment by mohammadgarmroodi** [comment]
> When running in dev mode:
> 
> ![image](https://user-images.githubusercontent.com/520883/78889631-efae1f80-7a5b-11ea-91bb-7497aa901830.png)
> 
> It eventually gets stuck requesting resources.

this warning shows beacause you are registering service worker on dev and production Mode...add this to hide this warning

**Comment by shadowwalker** [comment]
@Hainesy That warning doesn't matter, it is by design to let service worker to run in dev mode, because sometimes we need to debug functionality other than caching behaviors. You can disable in dev mode if you need to.

To help with the issue, can you clarify if this happens in just dev mode, or both dev and prod mode? Also help me understand what is stucking?

**Comment by cansin** [comment]
I have a similar problem. In my case, I am controlling the workflow myself in order to show a prompt to skip waiting (per https://github.com/shadowwalker/next-pwa/tree/master/examples/lifecycle ). But, "controlling" event never gets fired:

```js
import React, { useEffect } from "react";
import { useSnackbar } from "notistack";
import Button from "@material-ui/core/Button";

export default function Pwa() {
  const { closeSnackbar, enqueueSnackbar } = useSnackbar();

  useEffect(() => {
    if (
      typeof window !== "undefined" &&
      "serviceWorker" in navigator &&
      window.workbox !== undefined
    ) {
      const showSkipWaitingPrompt = () => {
        const handleOK = () => () => {
          window.workbox.addEventListener("controlling", async () => {
            await caches.delete("others");
            window.location.reload();
          });

          window.workbox.messageSW({ type: "SKIP_WAITING" });
        };

        const handleCancel = (key) => () => {
          closeSnackbar(key);
        };

        enqueueSnackbar(
          "A new version is available, reload to use it immediately?",
          {
            action: (key) => (
              <>
                <Button onClick={handleCancel(key)}>Cancel</Button>
                <Button
                  color="secondary"
                  disableElevation
                  onClick={handleOK(key)}
                  variant="contained"
                >
                  OK
                </Button>
              </>
            ),
            variant: "info",
            persist: true,
          }
        );
      };

      window.workbox.addEventListener("waiting", showSkipWaitingPrompt);
      window.workbox.addEventListener("externalwaiting", showSkipWaitingPrompt);
      window.workbox.register();
    }
  });

  return null;
}
```

Clearing the cache gets rid of the problem until the next time "waiting" or "externalWaiting" is called. Interestingly this is only happening for "dev" and not for "prod".

**Comment by shadowwalker** [comment]
@cansin It works fine for me. Maybe event listener doesn't like the async callback?

**Comment by vinkovsky** [comment]
> I have a similar problem. In my case, I am controlling the workflow myself in order to show a prompt to skip waiting (per https://github.com/shadowwalker/next-pwa/tree/master/examples/lifecycle ). But, "controlling" event never gets fired:
> 
> ```js
> import React, { useEffect } from "react";
> import { useSnackbar } from "notistack";
> import Button from "@material-ui/core/Button";
> 
> export default function Pwa() {
>   const { closeSnackbar, enqueueSnackbar } = useSnackbar();
> 
>   useEffect(() => {
>     if (
>       typeof window !== "undefined" &&
>       "serviceWorker" in navigator &&
>       window.workbox !== undefined
>     ) {
>       const showSkipWaitingPrompt = () => {
>         const handleOK = () => () => {
>           window.workbox.addEventListener("controlling", async () => {
>             await caches.delete("others");
>             window.location.reload();
>           });
> 
>           window.workbox.messageSW({ type: "SKIP_WAITING" });
>         };
> 
>         const handleCancel = (key) => () => {
>           closeSnackbar(key);
>         };
> 
>         enqueueSnackbar(
>           "A new version is available, reload to use it immediately?",
>           {
>             action: (key) => (
>               <>
>                 <Button onClick={handleCancel(key)}>Cancel</Button>
>                 <Button
>                   color="secondary"
>                   disableElevation
>                   onClick={handleOK(key)}
>                   variant="contained"
>                 >
>                   OK
>                 </Button>
>               </>
>             ),
>             variant: "info",
>             persist: true,
>           }
>         );
>       };
> 
>       window.workbox.addEventListener("waiting", showSkipWaitingPrompt);
>       window.workbox.addEventListener("externalwaiting", showSkipWaitingPrompt);
>       window.workbox.register();
>     }
>   });
> 
>   return null;
> }
> ```
> 
> Clearing the cache gets rid of the problem until the next time "waiting" or "externalWaiting" is called. Interestingly this is only happening for "dev" and not for "prod".

Hi @cansin ! Did you solve the problem?

**Comment by cansin** [comment]
I have not. And since moved away from using this approach.
