### ISSUE TITLE
offline mode not work!

### ISSUE THREAD

**Issue by mohammadgarmroodi** [shadowwalker/next-pwa#29]
Hi 
i cache all pages in next.config.js by NetworkFirst strategy and it works well
but when i navigate to second page and set the offline mode in application tab,i expect that when i refresh the second page it works in offline mode but it doesnot work !
but when i navigate to second page and refresh the second page then i set the offline mode in application tab ,and refresh the second page that work in offline mode as well !
(when i refresh the second page before set offline mode...the cache manager work goood and if i dont refresh the second page the cache manager doesnt load second page in offline mode)

please help...

**Comment by Robc24** [comment]
I'm getting the same thing.  Offline isn't working.  The service worker is registered but offline mode is gone.

**Comment by shadowwalker** [comment]
This is expected, as next/link use frontend routing, it won't trigger network fetch or cache
