### ISSUE TITLE
Prototype Pollution in node-jsonpointer

### ISSUE THREAD

**Issue by marcinincreo** [shadowwalker/next-pwa#293]
# Summary

jsonpointer  <5.0.0
Severity: moderate
Prototype Pollution in node-jsonpointer - https://github.com/advisories/GHSA-282f-qqgm-c34q

# Versions

- `next-pwa`:  `>=5.2.25`

# How To Reproduce

`npm audit`

**Comment by shadowwalker** [comment]
Fixed in latest version
