### ISSUE TITLE
[NPM audit / Snyk test] Required security update of json-schema

### ISSUE THREAD

**Issue by adrianpothuaud** [shadowwalker/next-pwa#298]
# Summary

Hello, 
I would like to inform you of a dependency security issue with json-schema

# Versions

- `next-pwa`:  5.4.1
- `next`: 12.0.4

# How To Reproduce

1. Run `npm audit` or `npx snyk test` in any repo using `next-pwa@5.4.1`

# Expected Behaviors

It would be nice if no error could be detected by dependency security checks like `npm audit` or `snyk`

# Screenshots

<img width="1137" alt="Capture d’écran 2021-12-02 à 10 03 33" src="https://user-images.githubusercontent.com/60715240/144390813-cc7f6985-e166-4fdd-ba98-876893faf69f.png">

# Additional Context

NA

**Comment by shadowwalker** [comment]
Fixed in `5.4.4`
