### ISSUE TITLE
No Controle over caching data from public folder

### ISSUE THREAD

**Issue by SonuKumar81800** [shadowwalker/next-pwa#306]
Hello Everyone.. 
I am Working on this website for pwa implementation

[https://d24qi6xrnoiehb.cloudfront.net/](https://d24qi6xrnoiehb.cloudfront.net/)

i am using pwa-next module 

and using next.config.js as 

```
const withPWA = require('next-pwa')({
  pwa: {
    dest: 'public',
    register: true,
    skipWaiting: true,
    runtimeCaching,
    // buildExcludes: [/public/$/],
    publicExcludes: ['!/public/**/'],
    // disable: process.env.NODE_ENV === 'development',
  },
});

```

now the problem is that i have large files in the public directry as shown in the image below:

![image](https://user-images.githubusercontent.com/45717030/147318534-1caff43a-2d98-470e-bda2-bff391e4bdd7.png)

when i deploy and open this for first time . it load almost 200  mb data in the cache memory. 

![image](https://user-images.githubusercontent.com/45717030/147318565-592cf141-6d36-4b39-aab9-b0115549422f.png)

 and it takes around 20 min to show this option for download app 
 
![image](https://user-images.githubusercontent.com/45717030/147318696-6d75d1e2-4196-4919-a1cc-a3e0cc0162b2.png)

how can i fix it ?

**Comment by vitormalencar** [comment]
hey @SonuKumar81800  
quick question have you tried the  `publicExcludes` config option
maybe this can help with your problem here

**Comment by SonuKumar81800** [comment]
yes @vitormalencar as you can see in my config i am using publicExcludes
`pwa: {
    dest: 'public',
    register: true,
    skipWaiting: true,
    runtimeCaching,
    // buildExcludes: [/public/$/],
    publicExcludes: ['!/public/**/'],
    // disable: process.env.NODE_ENV === 'development',
  },`

**Comment by zachrdz** [comment]
According to the documentation, the `public` folder is assumed from the `dest: 'public'` config, so your path should not include it

```
publicExcludes - an array of glob pattern strings to exclude files in the public folder from being precached.
default: ['!noprecache/**/*'] - this means that the default behavior will precache all the files inside your public folder but files inside /public/noprecache folder. You can simply put files inside that folder to not precache them without config this.
example: ['!img/super-large-image.jpg', '!fonts/not-used-fonts.otf']
```

Your code:
```
publicExcludes: ['!/public/**/'],
```
Try instead:
```
publicExcludes: ['!assets/**/*']
```

**Comment by SonuKumar81800** [comment]
Its working @zachrdz sir .
Thank you
