### ISSUE TITLE
Caching data from server api

### ISSUE THREAD

**Issue by mirik999** [shadowwalker/next-pwa#308]
Hi, how to disable caching specific data from "getServerSideProps". In my case i am getting old data but after refreshing page i'm getting latest data. But network tabs shows both of them. 
![Screen Shot 2021-12-28 at 14 24 27](https://user-images.githubusercontent.com/29675733/147563092-7ff9fb84-0bfc-4f9d-9457-ce06b32f86c0.png)
I want to keep only last data because it's dynamic always. 
I couldn't find any useful data from net so decided to ask here. Thanks.

**Comment by khuezy** [comment]
Hi have you looked into runtimeCache https://developers.google.com/web/tools/workbox/guides/generate-service-worker/cli

const config = {
  ...
  workboxOpts: {
   ...
    runtimeCaching: runtimeCache
  },

**Comment by shadowwalker** [comment]
Customize this https://github.com/shadowwalker/next-pwa/blob/3c029edf113921badd2f0058ae38d72a9d3f9fef/cache.js#L108 to be `NetworkFirst`
