### ISSUE TITLE
Using precaching with asset-prefix

### ISSUE THREAD

**Issue by TimoWilhelm** [shadowwalker/next-pwa#318]
In my Next.js App I serve all my static assets using a CDN with [asset-prefix](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix). However, the precaching requests are still targeting my host instead of my CDN.

Is there a way to get next-pwa to respect the asset-prefix for all `/_next/*` precaching requests?

**Comment by TimoWilhelm** [comment]
I managed to get it working somewhat using the  `manifestTransforms` setting like this:

```ts
manifestTransforms: [
  async (manifestEntries) => {
    const manifest = manifestEntries.map((m) => {
      if (!/^(?:[a-z]+:)?\/\//.test(m.url)) {
        // add cdn origin for relative urls
        m.url = `${cdnEndpoint}${m.url}`;
      }
      return m;
    });
    return { manifest, warnings: [] };
  },
],
```

That worked for most of the precached urls. However, the following URLs keep getting loaded from the host instead:
![image](https://user-images.githubusercontent.com/22396907/151794541-0bd1c3d8-a9fc-4c4f-a90a-48b4c6cd2f2a.png)

**Comment by shadowwalker** [comment]
For security, browser won't allow running service worker scripts from a different domain. So those must be served from your host or at least let the browser believe so.
