### ISSUE TITLE
Issue with service worker. middleware-runtime.js'

### ISSUE THREAD

**Issue by HT-Moh** [shadowwalker/next-pwa#323]
# Summary

Issue with service worker. 

![image](https://user-images.githubusercontent.com/34759569/153281821-add06bc7-33d7-487b-a4f2-4659f0e888d2.png)

Same with incognito window 

![image](https://user-images.githubusercontent.com/34759569/153282048-091f70bc-c721-4db6-8225-4533eccb0f8a.png)

![image](https://user-images.githubusercontent.com/34759569/153283598-5e200420-9ee6-4152-9c7d-9a595b92e793.png)

# Versions

- `next-pwa`:  5.4.4
- `next`: 12.0.10

# How To Reproduce

On `next.config.js` I imported `const runtimeCaching = require('next-pwa/cache')`  and add the pwa object
```javascript 
  pwa: {
    dest: 'public',
    disable: !isProduction,
    register: true,
    skipWaiting: true,
    runtimeCaching: runtimeCaching,
    //  issue exist with or without exclude
    buildExcludes: [
      /middleware-manifest\.json$/,
      /_middleware\.js$/,
      /middleware\.js$/
    ],
    mode: 'development'

    // dynamicStartUrlRedirect: '/api/auth/signin'
  },
```
I am using as well as well  nextjs [middleware](https://nextjs.org/docs/middleware) 
file `_middleware.tsx``
```
/* eslint-disable unicorn/filename-case */
// eslint-disable-next-line unicorn/filename-case
import { NextFetchEvent, NextRequest, NextResponse } from 'next/server'

const PUBLIC_FILE = /\.(.*)$/

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function middleware(request: NextRequest, event: NextFetchEvent) {
  const shouldHandleLocale =
    !PUBLIC_FILE.test(request.nextUrl.pathname) &&
    !request.nextUrl.pathname.includes('/api/') &&
    request.nextUrl.locale === 'default'

  return shouldHandleLocale
    ? NextResponse.redirect(`/en${request.nextUrl.href}`)
    : undefined
}
```
I tried as well custom RuntimeCaching, but same issue

**Comment by pascuflow** [comment]
Made a pr to fix this https://github.com/shadowwalker/next-pwa/pull/325
