### ISSUE TITLE
Issue with cache POST requests

### ISSUE THREAD

**Issue by favrio** [shadowwalker/next-pwa#324]
# Summary

When I try to cache POST requests by using the following strategy, I get errors at the console.

```
workbox-c103613c.js:formatted:346 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Request': Request body is already used
    at R.cachePut (workbox-c103613c.js:formatted:346:20)
    at async R.doneWaiting (workbox-c103613c.js:formatted:413:17)
    at async v.q (workbox-c103613c.js:formatted:505:17)

```

# Versions

- `next-pwa`: 5.4.4
- `next`: 12.0.10

# How To Reproduce

1. Config the cache config
```
runtimeCaching: [
      {
        urlPattern: ({ url }) => {
          const pathname = url.pathname
          if (pathname.startsWith('/api/')) return true
        },
        handler: 'NetworkFirst',
        method: 'POST',
        options: {
          cacheName: 'api-request-post',
          expiration: {
            maxEntries: 32,
            maxAgeSeconds: 24 * 60 * 60,
          },
          networkTimeoutSeconds: 10,
        },
      }
]
```
2. yarn build && yarn start on localhost
3. See error

# Screenshots

![image](https://user-images.githubusercontent.com/4222261/153331397-4f7e6465-4d13-4fa8-97a5-f4a4d17fcd55.png)

**Comment by favrio** [comment]
> HTTP caching is applicable only to idempotent requests, which makes a lot of sense; only idempotent and nullipotent requests yield the same result when run multiple times.

**Comment by shadowwalker** [comment]
You can't cache post requests
