### ISSUE TITLE
Cannot test _offline page

### ISSUE THREAD

**Issue by alirezavlz** [shadowwalker/next-pwa#328]
# Summary
Hello There,
Thanks for your great work. It's couple of month I'm using next-pwa in my project but the issue I cannot reproduce a situation to see the `_offline.js` page. I also used the examples to check but it is not working....am I missing something here?

**Comment by alirezavlz** [comment]
Also noticed that `fallbacks.images` is not working....
```js
    fallbacks: {
      image: '/images/black.jpg'
    }
```

**Comment by cdking007** [comment]
same issue facing fallback page _offline is not working in offline mode while it just reopening home page.
