### ISSUE TITLE
Custom workbox file naming

### ISSUE THREAD

**Issue by atuljain2995** [shadowwalker/next-pwa#330]
I want to rename the workbox file with a prefix to identify the workbox for different products. Is there any way I can achieve that ?

**Comment by atuljain2995** [comment]
I want the workbox file name to be like "xyz-workbox-12345.js"

**Comment by shadowwalker** [comment]
Workbox file content will the same, why do you want to create duplicate files? You can custom service worker file name by config `sw: 'service-worker.js'`

**Comment by atuljaingocomet** [comment]
Yes, I made changes from server side, and it worked. I'm multi-repo architecture, so it was causing a problem.

**Comment by atuljain2995** [comment]
Resolved
