### ISSUE TITLE
Allow `revision` property to be `null` on preaching

### ISSUE THREAD

**Issue by ammar-oker** [shadowwalker/next-pwa#336]
# Summary

The problem is that the `revision` property on precaching is always set to the `buildId` and changed on each build. This will cause an issue where the service worker will fetch ALL the pages on each build/release even the non-updated ones.

Next.js handles filenames hashing in a pretty convenient way using Webpack's `contenthash` (e.g. `[name].[contenthash].js`) which will only change the filename hash if the content of the file has changed.

And as described on Workbox docs [here](https://developer.chrome.com/docs/workbox/modules/workbox-precaching/#how-workbox-precaching-works),
> URLs that [already include](https://developer.chrome.com/docs/workbox/reference/workbox-build/#property-BasePartial-dontCacheBustURLsMatching) versioning information (like a content hash) are used as cache keys without any further modification.

By setting the `revision` property to `null` service worker will fetch only the updated pages on each build otherwise, it'll fetch all pages which will cause unnecessary network traffic.

# Versions

- `next-pwa`: 5.4.1
- `next`: 12.1.4

# How To Reproduce

1. Build the project with next-pwa
2. run the app in production mode
3. Monitor the network traffic, you'll see all the pre-cached files are fetched
4. update one file in your project and build again
5. run the app again, and you'll see all the pre-cached files are fetched again.

Link to minimal reproducing setup repository if any.
https://github.com/ammar-oker/next-pwa-example

# Expected Behaviors

Allow developers to optionally set the `revision` property to `null` therefore, the filename hash is used as the cache key.

**Comment by ammar-oker** [comment]
FYI, in Next.js [_Persistent Caching for Page Bundles_](https://nextjs.org/blog/next-9-5#persistent-caching-for-page-bundles) is supported in v9.5 and above.

**Comment by shadowwalker** [comment]
@ammar-oker This is good suggestion. It's better we put the revision using content hash. Made an update in version `5.5.0`, take a look: https://github.com/shadowwalker/next-pwa/commit/384a5138360c3c0eed114314dcb847704130603f

**Comment by ammar-oker** [comment]
Thanks a lot @shadowwalker!
