### ISSUE TITLE
offline-fallback-v2 don't routing to _offline.js page when offline 

### ISSUE THREAD

**Issue by Dieber** [shadowwalker/next-pwa#338]
# Summary

offline-fallback-v2 don't routing to _offline.js page when offline

# Versions

- `next-pwa`: latest
- `next`: ^12.1.0

# How To Reproduce

1. clone next-pwa offline-fallback-v2 example
2. start server, access localhost:3000
3. Go to DevTools, disable cache, set throtting to offline
4. refresh

# Expected Behaviors

Expect show  page which is writing in _offline.js

![1649144206(1)](https://user-images.githubusercontent.com/17017234/161702962-871a3833-d273-432b-bd64-a2342e5dbd6f.jpg)

# Screenshots
![1649144352(1)](https://user-images.githubusercontent.com/17017234/161703343-b53ec3a2-9ca9-4afa-a9a8-d30d3ad4ef89.jpg)

**Comment by shadowwalker** [comment]
This is working as expected for me. If you take a look at README instruction, it specifically says `yarn build && yarn start` instead of `yarn dev`. Can you try that?

**Comment by frinzekt** [comment]
I am also experiencing this too... I don't get rerouted to the `_offline.js` page. I just stick on the current page even after refresh
<img width="1025" alt="Screen Shot 2022-04-06 at 3 50 55 pm" src="https://user-images.githubusercontent.com/44391389/161923846-11fc411a-6cf5-4abf-971b-de16e075043c.png">

**Comment by frinzekt** [comment]
Relevant issue #328

**Comment by Dieber** [comment]
> This is working as expected for me. If you take a look at README instruction, it specifically says `yarn build && yarn start` instead of `yarn dev`. Can you try that?

yep, I certenly run the "npm run build" & "npm start" not "npm run dev", which I forgot mention...

**Comment by shadowwalker** [comment]
@Dieber @frinzekt You are visiting the `/` root path, which can be served by cache. If you take offline, then visit a path like `/foobar`, it will show the offline page for you. This is what this fallback feature all about. Normally if you build a blog website, user visited a new blog page like `/blog/some-new-page`, if user is online, he could visit the new blog normally and cache it, but if he is offline, he would be directed to a nice offline page.

**Comment by alirezavalizade** [comment]
I have same issue, none of fallback options working. Not offline page and not image fallbacks!

**Comment by Dieber** [comment]
> 

Thanks for your reply, I think your answer is helped me...

**Comment by bubuq3** [comment]
I got an error `Application error: a client-side exception has occurred (see the browser console for more information).` when I am offline (no internet connection) and enter a page where I got SSR data from graphCMS. when i reload (refresh page slide from top to down) then it shows my _offline.js page :/. What is it?

**Comment by bubuq3** [comment]
same here: got ann error `Application error: a client-side exception has occurred (see the browser console for more information).` and it doesn't route to _offline.js (if I slide from up to down - refresh a page) then it shows _offline.js page :/ what is it?
