### ISSUE TITLE
Service Worker not generated in public folder

### ISSUE THREAD

**Issue by mrmonat** [shadowwalker/next-pwa#370]
# Summary

Starting with version 5.5.5 when running `npm run build` no `sw.js` and no `workbox-*.js` file is generated in the `public` folder. When downgrading to 5.5.4 everything works as expected.

# Versions

- `next-pwa`: 5.5.5
- `next`: 12.2.3

# How To Reproduce

1. Setup a fresh installation of `next` with `next-pwa` (following the official next-pwa docs)
2. run `npm run build`
3. See `sw.js` and `workbox-*.js` only in `.next` folder but not in `public` folder.

# Additional Context

next.config.js:
```js
const withPWA = require('next-pwa')

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  pwa: {
    dest: 'public',
    register: true,
  }
}

module.exports = withPWA(nextConfig)
```

**Comment by tanaytoshniwal** [comment]
5.5.4 only works when we provide a version in package.json like "5.5.4"
and the same issue is repro for version: "^5.5.4"

**Comment by dymarchyk** [comment]
Same issue. next version 12.2.3 and next-pwa 5.5.4 not generating files.

**Comment by ArturNicolaiewskyPellicioli** [comment]
same issue...

**Comment by Gabrielpdev** [comment]
Same problem here !!!

**Comment by ArturNicolaiewskyPellicioli** [comment]
Temp fix: downgrade to 5.4.0v

**Comment by norbert-mosinski** [comment]
Solved by leaving the config empty:
```
const withPWA = require("next-pwa");

module.exports = withPWA({  
});
```

**Comment by agustints** [comment]
Same problem +1

**Comment by timmapuramreddy** [comment]
> Solved by leaving the config empty:
> 
> ```
> const withPWA = require("next-pwa");
> 
> module.exports = withPWA({  
> });
> ```

Tried but still the same issue

**Comment by timmapuramreddy** [comment]
> Temp fix: downgrade to 5.4.0v

Nextjs with 12.2.3 and PWA 5.4.0 is not working, still same issue

**Comment by cristian-talero** [comment]
Downgrade to next-pwa@5.5.4

**Comment by im-tridevsharma** [comment]
I just downgraded to next-pwa@5.5.4 with NextJs@12.2.3 
And working fine for me.

**Comment by priyansharma** [comment]
Next-pwa 5.5.5 have bug 
Please downgrade to 5.5.4 it will work

Thank you everyone

**Comment by juniorbatistadev** [comment]
I downgraded and still not wroking

**Comment by priyansharma** [comment]
![image](https://user-images.githubusercontent.com/55691501/183002716-23ea2927-d365-4ccc-8ffe-26c95b1aac86.png)

Try with fresh approach.

**Comment by Igrey1321** [comment]
Hi everyone. Need to remove this symbol  ^  in next-pwa": "^5.5.4" and install version 5.5.4

**Comment by juniorbatistadev** [comment]
> Hi everyone. Need to remove this symbol ^ in next-pwa": "^5.5.4" and install version 5.5.4

Yeah, I figured out this later. Thanks!

**Comment by meabed** [comment]
Could this be fixed soon?

**Comment by mrminnkhantnaing** [comment]
> Downgrade to next-pwa@5.5.4

This approach worked for me as well.

**Comment by sidd1707** [comment]
> I just downgraded to next-pwa@5.5.4 with NextJs@12.2.3 And working fine for me.

This works for me  "next-pwa": "5.5.4",

**Comment by Luskan777** [comment]
Same problem ...

**Comment by Jonathan-Vandenberg** [comment]
None of the versions working, tried all...

**Comment by syed-ammad** [comment]
Guyz Just install next-pwa@5.5.4 .

**Comment by iacobfred** [comment]
@shadowwalker what is the final resolution for this? The only "solution" mentioned in this thread is downgrading to 5.5.4, which seems to be incompatible with the new config format in `next.config.js` described in next-pwa documentation. This library is on version 5.6.0 now. Shouldn't the bug be fixed?

**Comment by Yorkshireman** [comment]
@iacobfred it looks like https://github.com/shadowwalker/next-pwa/pull/372 fixed this, so the latest `next-pwa` version should work fine.

**Comment by iacobfred** [comment]
@Yorkshireman thanks. I just realized that the problem was actually with my build process in my multistage Dockerfile. I was copying the `public` dir from the host rather than from the builder stage, so it didn't include the service worker files that were generated during the builder stage.

**Comment by famdude** [comment]
I still have the same problem with next 13.4 and next-pwa ^5.6.0

**Comment by 8kto** [comment]
Had the same issue with `^5.6.0`. 
Adding the manual copying to package.json seemingly fixed that:

```json
"postbuild": "cp build/sw.js build/workbox-* public/",
```
