### ISSUE TITLE
'disable' option not disabling pwa feature in development mode.

### ISSUE THREAD

**Issue by david-buck** [shadowwalker/next-pwa#371]
# Summary

My `next.config.mjs` file has `next-pwa` configured like so:

```
export default withPWA({
  pwa: {
    dest: "public",
    register: false,
    skipWaiting: false,
    dynamicStartUrl: false,
    runtimeCaching,
    disable: process.env.NODE_ENV === "development",
  }, ...
```
The `disable` option seems to be ignored, even if set to `disable: true` which leads to all the quirks that come with running next-pwa in development mode.

# Versions

- `next-pwa`: 5.5.5
- `next`: 12.2.3

# How To Reproduce

1. add `disable: true` option to `next.config.js`
2. yarn dev
3. see warnings in console:

```
warn  - GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
```

**Comment by phil-madpaws** [comment]
Using this as a workarond for now:

`module.exports = prod ? withPWA(nextConfig) : nextConfig;`

**Comment by piro0919** [comment]
I think it works fine with v5.5.4.
I'm sorry, but I haven't investigated the cause yet.

**Comment by ymchun** [comment]
seems related to this line: https://github.com/shadowwalker/next-pwa/blob/9d28c3be6aa6cc082a2ca87ba61117fff57ded8f/index.js#L338
`.pwa` config is deleted too early so that `webpack` function can't read any user config.

https://github.com/shadowwalker/next-pwa/blob/9d28c3be6aa6cc082a2ca87ba61117fff57ded8f/index.js#L56
the value of `pwa` variable is `{}`

**Comment by faisalamin001** [comment]
> Using this as a workaround for now:
> 
> `module.exports = prod ? withPWA(nextConfig) : nextConfig;`

it worked for me as well, thanks!
@phil-madpaws
