### ISSUE TITLE
sw.js doesn't generated in public folder after yarn next build

### ISSUE THREAD

**Issue by pantemon** [shadowwalker/next-pwa#374]
# Summary

I have tried different options in case of using Next.js older than version 9 and they solved my problem, but I'm using Next.js version 9 or newer that's why I shouldn't not use this.

# Versions

- `next-pwa`: ^5.4.1
- `next`: ^12.2.3

# How To Reproduce

1. `npx create-next-app --example progressive-web-app progressive-web-app`
2. cd progressive-web-app
3. yarn build

# Expected Behaviors

I expect that after `yarn next build` **sw.js** will be added to `/public` directory.

# Screenshots

Here you can see that sw.js is not added to public directory.
`Service worker: /home/pantemon/trash/progressive-web-app/.next/sw.js`

![image](https://user-images.githubusercontent.com/96831202/181995609-20c8699c-f0eb-4be2-b45b-8d23288e9649.png)

**Comment by dreamqip** [comment]
Same issue

**Comment by pantemon** [comment]
Solved the problem by removing **^** from `next-pwa` version in **package.json**.

Before: `"next-pwa": "^5.5.4"`
After: `"next-pwa": "5.5.4"`
