### ISSUE TITLE
Navigation doesn't work in offline fallback page

### ISSUE THREAD

**Issue by SahilAggarwal2004** [shadowwalker/next-pwa#387]
# Summary

What can I help with? Please keep this clear and concise.

# Versions

- `next-pwa`: 5.5.5
- `next`: 12.2.0

Everything works fine when I try to access a page which is not cached in offline mode, the /_offline fallback page in shown. But in there when I try to navigate to some other page (that is cached) using the navbar containing <Link> from 'next/link', it doesn't navigate to the cached pages.

**Comment by SahilAggarwal2004** [comment]
Sorry! I was doing a silly mistake...

**Comment by skellertor** [comment]
@SahilAggarwal2004 can you share what you were doing? I am having the same issue

**Comment by SahilAggarwal2004** [comment]
Ohh, actually that was a very silly mistake from my side. There was some problem with the z-index of my navbar. Try increasing the value of z-index of your navbar.

**Comment by SahilAggarwal2004** [comment]
> @SahilAggarwal2004 can you share what you were doing? I am having the same issue

Ohh, actually that was a very silly mistake from my side. There was some problem with the z-index of my navbar. Try increasing the value of z-index of your navbar.
