### ISSUE TITLE
Cannot use a custom NextConfig

### ISSUE THREAD

**Issue by AntoineKM** [shadowwalker/next-pwa#405]
# Summary

What can I help with? Please keep this clear and concise.

You might accept custom NextConfig for people which are using Sentry for example, or things like ``poweredByHeader``, so allow all properties

I have this error with my custom NextConfig:
```
- The root value has an unexpected property, 17, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, red
```

# Versions

- `next-pwa@5.6.0`: 
- `next@12.1.0`:

# How To Reproduce

Quick example with ``poweredByHeader``

```
// next.config.js
module.exports = withPWA({ poweredByHeader: false, });
```

# Expected Behaviors

You gonna have an error like: ``- The root value has an unexpected property, 0, which is not in the list of allowed properties (poweredByHeader)``

# Screenshots

![image](https://user-images.githubusercontent.com/54948363/189902362-1a2f3b7f-9983-47d2-8c78-baeb8b0958fb.png)

# Additional Context

Work super fine with these versions:
- `next-pwa@5.5.6`: 
- `next@12.1.0`:

**Comment by eins78** [comment]
there is a breaking change (see #411), and the way to use the plugin has changed. adapting your example:

```js
// next.config.js
module.exports = addWithPWA(/* pwa conf */)({ poweredByHeader: false, });

```
