### ISSUE TITLE
[question] additionalManifestEntries revision ID

### ISSUE THREAD

**Issue by harshzalavadiya** [shadowwalker/next-pwa#41]
in `next.config.js` custom configuration is there any way to get `revision` if we have provided `additionalManifestEntries` for precaching routes? or we can just randomly generate and provide it?

because providing `null` actilly caches it sorta permanantly and doesn't reflect changes after hard reload

Here's a sample behaviour on precache route with null as revision build id reverts back even after empty cache and hard reload
![Peek 2020-05-05 17-17](https://user-images.githubusercontent.com/5774849/81062990-a33bef80-8ef4-11ea-8332-520deee6ac75.gif)

**Comment by shihabus** [comment]
Same issue.
You can use some webpack plugin to pass revision id inside a custom service worker. This service worker you can later pass on to the workbox using injectManifest mode.

**Comment by harshzalavadiya** [comment]
In my case there was no need of webpack plugin, I just passed random revision ID on each build

```js
additionalManifestEntries: [
  { url: "/", revision: RANDOM_ID }
]
```

**Comment by shadowwalker** [comment]
@harshzalavadiya passing a random id would work, but best practice is using MD5 checksum for each file because it will help workbox understand the file is modified and need to update the cache.
