### ISSUE TITLE
Does not register a service worker that controls page and 'start_url'

### ISSUE THREAD

**Issue by rakhmonovbekzod** [shadowwalker/next-pwa#418]
Next pwa in not working in production. This is my next.config.js
![image](https://user-images.githubusercontent.com/84036205/197109995-2f19059e-4d6f-4dbf-b6de-ef06f1c302bd.png)
How to fix this error?

**Comment by rakhmonovbekzod** [comment]
![image](https://user-images.githubusercontent.com/84036205/197110184-748430d4-f82c-424d-8249-40bcfdf1c1e9.png)
![image](https://user-images.githubusercontent.com/84036205/197110314-6cc95c17-f697-4116-bfbf-8f625d4d777b.png)

my package.json and manifest.json

**Comment by qutek** [comment]
@rakhmonovbekzod have you tried to set the `start_url` to the `/app` as well?

**Comment by rakhmonovbekzod** [comment]
> @rakhmonovbekzod have you tried to set the `start_url` to the `/app` as well?
I register service-worker in _app.js and now all okey
