### ISSUE TITLE
Failed to execute 'add' on 'Cache'

### ISSUE THREAD

**Issue by rejoanahmed** [shadowwalker/next-pwa#443]
**### next-pwa config**
 const withPWA = require('next-pwa')({
  dest: 'public',
  cacheOnFrontEndNav: true,
  disable: false,
})

I have custom 404.tsx page.

anytime the user hits 404 page, the error appears 

**### Unhandled Runtime Error
TypeError: Failed to execute 'add' on 'Cache': Request failed**

this happens only when online. but when offline, the error doesn't occur.

is there any configs i need to add?

**Comment by panta82** [comment]
I am getting this.

What was the solution?
