### ISSUE TITLE
When service worker is modified, latest SW is not getting updated in the client.

### ISSUE THREAD

**Issue by shihabus** [shadowwalker/next-pwa#45]
Set up:
We are using workbox in injectManifest mode with next-pwa.

Context:
There is an offline fallback view which should be precached.
Inside my custom service worker (srcSW), I am achieving as

const CACHE_NAME = "offline-html";
const FALLBACK_HTML_URL = "/offline";
self.addEventListener("install", async event => {
    event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.add(FALLBACK_HTML_URL)))
})
myPWAConfig looks like:

return {
        disable: process.env.NODE_ENV !== "production",
        register: true,
        scope: "/",
        sw: "/sw.js",
        swSrc: "./swSrc.js",
        maximumFileSizeToCacheInBytes: mb1,
        include: [/(pages\/offline.js)$/],  // same offline page
        exclude: [/.*\.map$/],
    }
Each time I do an update in view/offline.js the service worker is not getting updated on client refresh. I have to do an explicit service worker update.

Outside next-pwa I was trying the same with work-box build and it was working as expected.

**Comment by shadowwalker** [comment]
Are these regex correct?
```
include: [/(pages/offline.js)$/], // same offline page
exclude: [/.*.map$/],
```
Don't you need some escapes?
```
include: [/pages\/offline\.js$/], // same offline page
exclude: [/.*\.map$/],
```

**Comment by Shihab-Duzno** [comment]
Should I be trying out `/pages/offline.js` caching during the SW install event?
```
const CACHE_NAME = "offline-html";
const FALLBACK_HTML_URL = "/offline";
self.addEventListener("install", async event => {
    event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.add(FALLBACK_HTML_URL)))
});
```

What I was really curious is, with workbox should we still need to do this?

**Comment by shihabus** [comment]
Should I be trying out `/pages/offline.js` caching during the SW install event?
```
const CACHE_NAME = "offline-html";
const FALLBACK_HTML_URL = "/offline";
self.addEventListener("install", async event => {
    event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.add(FALLBACK_HTML_URL)))
});
```

What I was really curious is, with workbox should we still need to do this?

**Comment by Shihab-Duzno** [comment]
I was trying the same w/o `next-pwa` using `workbox-cli`. Overthere, adding the files to be cached solved my all problems. I never did the manual cache. Am I missing something with my config while using `next-pwa`?
