### ISSUE TITLE
path.join is used to join non-URLs which breaks `now dev` on Windows

### ISSUE THREAD

**Issue by anaisbetts** [shadowwalker/next-pwa#47]
Running `now dev` on a next-pwa enabled app on Windows will result in an unbootable app, because scope will incorrectly be generated as `"\"`, which will be parsed as an unterminated string. This is because many places in the code concatenate URLs with `path.join`, when they probably just want `[someOther, thing].join('/')`

**Comment by shadowwalker** [comment]
Mark this as a bug
https://github.com/shadowwalker/next-pwa/blob/502ed0c9e222bf8b1a5cb15676e566eed656c2f2/index.js#L60-L61
https://github.com/shadowwalker/next-pwa/blob/502ed0c9e222bf8b1a5cb15676e566eed656c2f2/index.js#L146-L149

**Comment by Pytal** [comment]
@shadowwalker ETA for the hotfix?

**Comment by shadowwalker** [comment]
This should be fixed
https://github.com/shadowwalker/next-pwa/commit/fc16e390a3b7fe67d9bdb288e977be6d19c69fbf
