### ISSUE TITLE
next-pwa does not work on a development environment

### ISSUE THREAD

**Issue by lightbluepoppy** [shadowwalker/next-pwa#478]
There's a issue #143  that refers to the same problem. 

> When you want to test offline of the web app, simply use yarn start instead of yarn dev.

It does not make sense since you have to run `next build && next start` every time you make changes to your codebase. Using `next build && next start` instead of `next dev` on the development environment is inefficient. `mode: 'production'` in `next.config.js` seems not working as well.

**Comment by itbeginswithi** [comment]
@lightbluepoppy, did you find a better solution?
