### ISSUE TITLE
Homepage is not triggering cache repopulation

### ISSUE THREAD

**Issue by dinohamzic** [shadowwalker/next-pwa#48]
Hello, I'm having an issue with the service worker specifically when opening the homepage (index.js) of my app.

The request to `localhost:7777` is completely relying on the offline cache, breaking some functionality that is dependent on cookies.

On the other hand, when visiting any other page (`/login`, `/shop`, etc.) the request by the Service Worker's install handler to populate the offline cache is made every time, which should also be the behavior of the homepage.

Homepage (no call):
![Screen Shot 2020-05-08 at 14 27 43](https://user-images.githubusercontent.com/31952489/81405540-239e6280-9138-11ea-8008-0f5577ac3f10.png)

Any other page:
![Screen Shot 2020-05-08 at 14 28 30](https://user-images.githubusercontent.com/31952489/81405602-46c91200-9138-11ea-8b69-f864721b4ece.png)

How could I replicate this behavior also on the homepage? I'm not sure if this is a bug or something I should configure.

Info:
- the app doesn't have a custom `server.js` file
- in `next-pwa`'s config I only added `dest: 'public'`

**Comment by tonydefaria** [comment]
Exactly the same issue on this end.

**Comment by shadowwalker** [comment]
@dinohamzic I couldn't repro this issue. If anyone is facing the same issue, please feel free to throw me a repro example.

**Comment by shadowwalker** [comment]
Should be fixed with version 3.0+
Example for cookies: https://github.com/shadowwalker/next-pwa/tree/master/examples/cookie
