### ISSUE TITLE
About next.js's upcoming revalidate property

### ISSUE THREAD

**Issue by kush-agra** [shadowwalker/next-pwa#49]
Not really and issue but wanted to chime you in on the feature and it's conversation
https://github.com/zeit/next.js/discussions/11552#discussioncomment-12285

We were wondering how incremental builds will work with next-pwa, it generates a build id at runtime so I guess it would never know that a page was rebuilt?

**Comment by shadowwalker** [comment]
It use the same build Id from `next.js` everytime there is a new build. The build id is used as revision id, so it knows there is a new build of the page.

**Comment by kush-agra** [comment]
even if it is rebuilt not at the first build time but at a later phase? great then thanks :)

**Comment by shadowwalker** [comment]
@kush-agra I see your point, I think in that case, it doesn't apply.
