### ISSUE TITLE
delete cookies from service worker

### ISSUE THREAD

**Issue by rafinskipg** [shadowwalker/next-pwa#50]
Hello, thanks for the project. I have a question about how to delete cookies from the service worker for auth sessions?

I have a cookie based session and the logout works fine without next-pwa, but when I use the serviceworker the user never gets logged out. 

Do you have any information on how to delete the session? thanks

**Comment by shadowwalker** [comment]
I think you can delete or clear cookies after user hit the log out button.

**Comment by rafinskipg** [comment]
hello @shadowwalker thanks for the answer. In case anyone needs a more detailed explanation:

````
 // Invalidate caches for service worker
    await caches.keys().then(function(keyList) {
      return Promise.all(keyList.map(function(key) {
        return caches.delete(key);
      }));
    })

````

**Comment by alexvilchis** [comment]
Hi there, I am having this issue too. @rafinskipg Could you tell me where to put such code? Where does `caches` come from?

**Comment by alexvilchis** [comment]
Nevermind, I just saw it's on the browser, thanks!

**Comment by alexvilchis** [comment]
Well, this didn't work for me. Deleting all cache entries causes a weird behaviour that shows a the browser offline page when the server is in fact running.


@rafinskipg How did you manage the cache strategies for protected routes (that sometimes return a 3xx code)?

**Comment by rafinskipg** [comment]
hello @alexvilchis , what i do is delete the cache when the user press logout, and after that do a redirect to the login page. And then everything is fine.

**Comment by alexvilchis** [comment]
Interesing, did you modify the default runtimeCaching config?

**Comment by rafinskipg** [comment]
I didnt change anything else
