### ISSUE TITLE
Last release was in Dec 18, 2022, please use DuCanhGH/next-pwa

### ISSUE THREAD

**Issue by tzoor-rozental** [shadowwalker/next-pwa#503]
This repo is unmaintained, @DuCanhGH picked it up.

https://github.com/DuCanhGH/next-pwa

**Comment by DuCanhGH** [comment]
Please, don't go around spamming in other people's repo like that. There are ample issues regarding the lack of maintenance here already.

**Comment by tzoor-rozental** [comment]
after checking

> Please, don't go around spamming in other people's repo like that. There are ample issues regarding the lack of maintenance here already.

i went over all the issues before opening this one and could not find such issues, a couple of issues look like they are about this but actually are not.
and because the author did not announce their intentions in any way, opening this issue such that its the first in the list is the only way i could think of to help unsuspecting individuals take notice.

**Comment by DuCanhGH** [comment]
@tzual #482 and #424. We didn't even need more than one issue, and there are now 3. You simply didn't search carefully enough. Also, I don't see the point in announcing that. This package still works just fine for Pages Router, and those wanting App Router support and/or proper maintenance can just do a simple Google search. The last time I looked there were already a lot of blogs and threads regarding this. Those in need will eventually come. Don't disturb the maintainers here.

**Comment by tzoor-rozental** [comment]
@DuCanhGH i understand, as you wish.
