### ISSUE TITLE
Next-PWA is not registering my service worker

### ISSUE THREAD

**Issue by elVengador** [shadowwalker/next-pwa#506]
# Summary

after install next-pwa and setup my next.config.js, Im running my aplication and there is not registered my service worker on my browser, I checked the path

# Versions

- `next-pwa`: ^5.6.0
- `next`: 14.1.2

# How To Reproduce
I setup my next.config.js
```js
/** @type {import('next').NextConfig} */
const nextConfig = {};

import nextPWA from 'next-pwa'
const withPWA = nextPWA({
    dest: 'public'
    register: true,
})
export default withPWA(nextConfig)
```
then run my application and check my browser

# Expected Behaviors

my service worker should be registered automatically

# Screenshots

there is no registered service worker:
<img width="715" alt="image" src="https://github.com/shadowwalker/next-pwa/assets/27080940/3603725c-b0c0-4aea-afae-dc1a2cc55b70">

but ther is the sw.js in the path:
<img width="527" alt="image" src="https://github.com/shadowwalker/next-pwa/assets/27080940/7d5a520c-8068-454a-988b-df82bffb17d2">

**Comment by elVengador** [comment]
I solved adding a `Script` in my Layout file from NextJs to call `sw.js` and that register my service worker

**Comment by hmh10098** [comment]
Can you give me an example script? I'm facing this issue too @elVengador

**Comment by vaclav-stummer** [comment]
@elVengador could you describe how did you solve the problem?

**Comment by vaclav-stummer** [comment]
I tried everything that I found in the issues related to the service worker registration. I wasn't able to make it running with `"next": "14.2.4"` and `"next-pwa": "5.6.0"`. So I was forced to use https://www.npmjs.com/package/@ducanh2912/next-pwa which works fine

**Comment by elVengador** [comment]
Hi @hmh10098 and @vaclav-stummer , I'm sorry for answer later
You can register a service worker with:
```js
<Script id="my-sw">
        {` 
          if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js')
          else console.warning("Ups, your navigator doesn't support service worker, offline feature wont work, update your browser or chose other modern browser")
        `}
</Script>
```

Aditionally, undestanding the React life cycle and the service worker life cycle is posible to set up all witout libraries like Next-PWA or Workbooks

**Comment by nandubatchu** [comment]
I too faced this. But this works in localhost - only in production build pipeline - something causes this!
