### ISSUE TITLE
Custom Worker to prevent default installation

### ISSUE THREAD

**Issue by LucasMallmann** [shadowwalker/next-pwa#52]
Hi there!

I'm trying to block the default installation prompt "Add to Homescreen" as I want to provide a custom install experience!

As stated in this article: https://web.dev/customize-install/ I had to listen to the 'beforeinstallprompt' event, and work from there.

I followed the examples in this repo to use a custom worker, by creating a `worker/index.js` in the root of my project. All I wrote in that index is to prevent the default installation prompt, like this:
```js
self.addEventListener('beforeinstallprompt', (e) => {
  // Prevent the mini-infobar from appearing on mobile
  e.preventDefault();
});
```

This worker is being loaded to the public folder, as expected...but the "Add to Homescreen" is still appearing :/ Any idea on how to acomplish this, please?

**Comment by shadowwalker** [comment]
You might want disable 
https://github.com/shadowwalker/next-pwa/blob/492eea7a69e5200ab038aafe91c354a76454859c/examples/lifecycle/next.config.js#L6-L7

**Comment by LucasMallmann** [comment]
Closing the issue, since I found out that I could use the window.addEventListener on my React components!
