### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch

### ISSUE THREAD

**Issue by raphtlw** [shadowwalker/next-pwa#53]
I'm using next.js 9+ and i'm getting an error when the page is loaded (in production).

```
Uncaught (in promise) TypeError: Failed to fetch
```

The error occurs in sw.js. Also, the service worker does not work.

**Comment by shadowwalker** [comment]
Are you referring to the `next-9` example?

**Comment by raphtlw** [comment]
@shadowwalker Yep

**Comment by raphtlw** [comment]
@shadowwalker I just found the issue. It is because the service worker tried to fetch a font from the website's static folder (https://igottech.news/_next/static/media/ProximaNova-Regular.c4c3616c5577f9e7ef87762dea50caa2.woff).

**Comment by elsigh** [comment]
I have the same error but not for a font but for loading "/" - how did you debug/fix the issue here @raphtlw ?

You can see my site behavior live at https://songbook.studio - just load, switch to offline and refresh

**Comment by vidyu** [comment]
@elsigh Did you resolve your problem? I'm facing the same issue now. Failed to fetch `/`

**Comment by vdjurdjevic** [comment]
@elsigh Having the same issue with "/"..

**Comment by jahirfiquitiva** [comment]
I'm also facing this issue, although I'm not sure what's causing it

**Comment by g-farrow** [comment]
Is this a duplicate of #160 ?
