### ISSUE TITLE
sw.js file is not generate when building

### ISSUE THREAD

**Issue by SanskarSans** [shadowwalker/next-pwa#54]
I dont have any sw.js file inside public folder when building. This is how I am using next-pwa

```javascript
const withPlugins = require("next-compose-plugins");
const optimizedImages = require("next-optimized-images");
const withPWA = require("next-pwa");

module.exports = withPlugins(
    [optimizedImages],
    [
      withPWA({
        pwa: {
          dest: "public",
        },
      }),
    ]
);
```

**Comment by shadowwalker** [comment]
Have you tried not use `next-compose-plugins`?
I've never used that library, that help you separate the configurations visually, but it doesn't separate the interaction side effect between plugins.

**Comment by LucasMallmann** [comment]
@SanskarSans maybe your `next-compose-plugins` configuration is wrong. I use this lib too, but I write my configurations differently.

```javascript
const withPlugins = require('next-compose-plugins');

module.exports = withPlugins([
  [
    withPWA,
    {
      target: 'serverless',
      poweredByHeader: false,
      assetPrefix: basePath,
      pwa: {
        dest: 'public',
        subdomainPrefix: basePath,
      },
    },
  ],
  [
    withImages,
    {
      assetPrefix: basePath,
    },
  ],
  ...nextConfig,
]);
```

**Comment by LucasMallmann** [comment]
Inside the array, you must pass the library instance as the first parameter, and the configuration in the second parameter. Maybe that's where you're missing something.

**Comment by marianyp** [comment]
I'm having this issue as well, and I think my configuration is valid too.

```js
const withPWA = require("next-pwa")
const withPlugins = require("next-compose-plugins")
const withCSS = require("@zeit/next-css")
const withSass = require("@zeit/next-sass")

module.exports = withPlugins([
  [
    withPWA,
    {
      pwa: {
        dest: "public",
      },
    },
  ],
  withCSS,
  [
    withSass,
    {
      webpack(config, options) {
        config.module.rules.push({
          test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
          use: {
            loader: "url-loader",
            options: {
              limit: 100000,
            },
          },
        })

        return config
      },
    },
  ],
])

```

Everything builds fine except for **next-pwa**. There's no error or anything, it just doesn't generate a sw.js for my app, when it should be.

**Comment by shadowwalker** [comment]
@SanskarSans I see have figured out about this issue, maybe you could help @marianyp on this one.

**Comment by nilaeus** [comment]
I am also getting this issue, and I am not using any other plugins.

**Comment by SanskarSans** [comment]
@marianyp  can you try something like this first to test if this one works for you or not?

```javascript
const withPlugins = require("next-compose-plugins");
const optimizedImages = require("next-optimized-images");
const withPWA = require("next-pwa");

module.exports = withPlugins(
  [optimizedImages],
  withPWA({
    pwa: {
     dest: "public",
    },
  }),
);
```

Also i don't think you will need withCss plugin for 9+ version.
