### ISSUE TITLE
wrong precacheAndRoute entry in sw.js for dynamic routes

### ISSUE THREAD

**Issue by harshzalavadiya** [shadowwalker/next-pwa#55]
### Demo
![pwa-precache-error](https://user-images.githubusercontent.com/5774849/83291547-24418a80-a206-11ea-8da4-9a10957f47c1.gif)
> Please open this GIF in new window to proper view

as you can see when hitting precached route for the first time in offline scenario leaves page non interactive due to supported js file resulting in 404

### Minimal Reproducable Example
https://github.com/harshzalavadiya/next-pwa-precache-bug

### Live Example
https://onwd3.now.sh/

currently generated `sw.js` file has non encoded square brackets in `precacheAndRoute` as shown below
![image](https://user-images.githubusercontent.com/5774849/83291761-84383100-a206-11ea-9bad-69933872af3c.png)

but after manually editing `sw.js` entry like below it works
![image](https://user-images.githubusercontent.com/5774849/83292161-41c32400-a207-11ea-8c5a-8804f9d6def1.png)

p.s. basically my end goal was to precache `/hello/[name]` and make it work dynamically with any route but seems it's not diretly possible so I'm adding `/hello/xyz` route to cache at runtime

**Comment by shadowwalker** [comment]
That seems a valid feature request

**Comment by shadowwalker** [comment]
Solve with version `2.5.0`.
Please feel free to close this issue.

**Comment by harshzalavadiya** [comment]
Thank you
