### ISSUE TITLE
Difference to next-offline?

### ISSUE THREAD

**Issue by BjoernRave** [shadowwalker/next-pwa#6]
Hey, what's the difference to this package?

https://github.com/hanford/next-offline

They also integrate workbox, why did you not use that?

**Comment by shadowwalker** [comment]
This package is similar to `next-offline` and both did a good job. When I first tried out `next-offline`, it's not using latest version of workbox and the configurations are confused to me. So I decided to work on my own and came up with simpler and robust solution. 

My package is simpler and a bit more opinionated and I would try to keep everything up to date.

**Comment by findela** [comment]
@shadowwalker you saved my day! there are no as simple as like your's package are in search made with Next.js. Keep updating this package so people who are new to Next can easily install PWA on his machine as it's the trend. ready to serve you as many coffee you like to take ;-)
