### ISSUE TITLE
"globIgnores" is not a supported parameter

### ISSUE THREAD

**Issue by LucasMallmann** [shadowwalker/next-pwa#64]
I'm trying to have more control over the routes and precached files. I'm using GenerateSW strategy to generate my service worker, and according to the workbox documentation, I could pass the `globIgnores` parameter to the generateSW class so that I could match files to always exclude when generating the precache. But I'm running into this error:

![image](https://user-images.githubusercontent.com/23031413/84949363-7c600400-b0c3-11ea-8bda-1e795a078b53.png)

**Comment by LucasMallmann** [comment]
Actually as I was debugging here, I found out that this seems to be an issue with the workbox-webpack-plugin itself.

**Comment by shadowwalker** [comment]
It's likely things have been changed on workbox and documentation is not up to date

**Comment by LucasMallmann** [comment]
Makes sense, I was trying to debug everything, but it was worthless. Another question @shadowwalker , how can I have control over the `precache` configuration? My application is pre-caching the homepage route and it's causing weird behaviors.

For example, I have an application that it's nested inside a subLocation. Eg.: `/site-builder` is an application that it's running nested in `/`. But as you can see, it's pre-caching the route `/site-builder`, which leads to having an outdated version of this application sometimes.

I wonder if I could configure which routes to precache or not, but I still could not figure it out.

![image](https://user-images.githubusercontent.com/23031413/84966758-b68fcc80-b0e8-11ea-9ede-359ff9989616.png)

**Comment by shadowwalker** [comment]
Closed with PR
