### ISSUE TITLE
Caching Document Request

### ISSUE THREAD

**Issue by kdelmonte** [shadowwalker/next-pwa#69]
First of all, thank you for this awesome project.

I am having an issue where my server side rendered page which is completely dynamic is being cached. 

I think this is happening because of [this line](https://github.com/shadowwalker/next-pwa/blob/master/index.js#L150).

Could we disable this line by adding a configuration option? If so, I could contribute with a PR.

Thanks!

**Comment by kdelmonte** [comment]
Please disregard... #66 takes care of this.

**Comment by LucasMallmann** [comment]
@kdelmonte actually I also had trouble with this line, but in fact, I don't think we need the #66 to be implemented.

Try to do this: in your `next.config.js` file, please add the configuration:
```js
{
  ...
  additionalManifestEntries: []
}
```

With the additionalManifestEntries being an array, it won't go inside this condition https://github.com/shadowwalker/next-pwa/blob/master/index.js#L140.

If you just want to remove the home page from the cache, try to include the files you want to precache in `additionalManifestEntries`. Eg.:
```js
{
  additionalManifestEntries: ['**/*.png', '**/*.svg', '**/*.css'] // this will precache every image, svg, and css files.
}
```

**Comment by kdelmonte** [comment]
@LucasMallmann I still think your PR adds an excellent option. I don't see why it would not be merged. In the meantime, I will use your solution above. tyvm!
