### ISSUE TITLE
Example for Inject Manifest Plugin

### ISSUE THREAD

**Issue by LucasMallmann** [shadowwalker/next-pwa#71]
I think it would be a great feature to add an example with the InjectManifest plugin. Now, there are only examples using the GenerateSW.

Using the InjectManifest is a little more complex, and I think it would help a lot of people that are searching for an implementation with this plugins.

**Comment by shadowwalker** [comment]
In general, there is no need to use InjectManifest, custom worker and `workbox-window` can satisfy most of the use cases. But if you create a clean example, I could merge it in.

**Comment by LucasMallmann** [comment]
Yeah, the custom-worker and `workbox-window` can cover almost all edge cases. But I'd like to implement a push notification system for example, and idk if this feature could be covered just by the custom worker or workbox, since the documentation talks about Inject Manifest when implementig a push notification system

![image](https://user-images.githubusercontent.com/23031413/86136876-f54b5c80-bac2-11ea-9b6a-62ecb3f21e3c.png)

**Comment by shadowwalker** [comment]
It can be done with custom worker as well

**Comment by shadowwalker** [comment]
@LucasMallmann Here you go
https://github.com/shadowwalker/next-pwa/tree/master/examples/web-push

**Comment by LucasMallmann** [comment]
Oh, that is awesome @shadowwalker ! Thank you very much for this implementation. Good to know that it works with custom worker instead of injectManifest!

**Comment by IamSAL** [comment]
hi,

is there any examples that show injectManifest? I need more control of worker(need to inject self.WB_MANIFEST). its undefined with generateSW
