### ISSUE TITLE
[Question] Are there breaking changes to v3? Can we see release notes?

### ISSUE THREAD

**Issue by DinerIsmail** [shadowwalker/next-pwa#74]
Hello, I was wondering if there's a place where we can view a changelog/release notes? I would update to the latest major version (3.x.x) but I'm not doing that for now in case there are breaking changes.
Thank you!

**Comment by shadowwalker** [comment]
There is no change log currently. But there shouldn't be any breaking changes. Major updates are optimizing caching strategies. Home route is no longer precached and remove font awesome from default cache and make others runtime cache Network First

**Comment by DinerIsmail** [comment]
Ok I see, thank you @shadowwalker for the quick reply.
