### ISSUE TITLE
How to use next-pwa with the apollo client?

### ISSUE THREAD

**Issue by sakhmedbayev** [shadowwalker/next-pwa#76]
Sorry in advance for asking a question here!

I wonder how to use "next-pwa" with the Apollo client? More specific how to persist network data for the offline mode?

**Comment by shadowwalker** [comment]
You can add the route to the `runtimeCaching`

**Comment by paales** [comment]
I would suggest using something like `apollo-link-persist` to cache your Apollo Client store and do the offline stuff there?
