### ISSUE TITLE
# of users using PWA

### ISSUE THREAD

**Issue by pbteja1998** [shadowwalker/next-pwa#77]
Hi,
Is there a way to know the number of users that have installed PWA and using it (vs) users using the normal web application?

**Comment by shadowwalker** [comment]
It's going to be hard to make it accurate, but you can checkout this example:
https://github.com/shadowwalker/next-pwa/blob/91485c62f86ad78b46ebaf2f3e2beffd3b0968a5/examples/lifecycle/pages/index.js#L11-L14

Add some script to collect numbers to your server API
