### ISSUE TITLE
Cannot serving old version of precaching since home (/) being cached by networkfirst in v3.0.x

### ISSUE THREAD

**Issue by jingz** [shadowwalker/next-pwa#81]
# Summary

Due to we have to provide on-demand PWA update. ( offer page reload )

https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users

With the new version. Home page (`/`) is cached by `NetworkFirst` strategy that make new version of pre-caches used immediately after user refresh or re-open the app. even manually handling skipWaiting and register.

as follow from `lifecycle` example.
https://github.com/shadowwalker/next-pwa/tree/master/examples/lifecycle

# How To Reproduce

1. update to v3.0.x and follow `lifecycle` example repo.
2. build and install pwa app into mobile.
3. rebuild again with minor update.
4. the new version is replaced without confirmation from user.

# Expected Behaviors
The new precaches should be used after user confirmation.

**Comment by shadowwalker** [comment]
This is actually not a "real" bug, it's implemented this way to satisfy the cookie use case. I will make an update to satisfy your use case. But remember, this will not work well if you redirect user to an sign in page if user is not login

**Comment by shadowwalker** [comment]
Please see in this example (update `next-pwa` to `3.1.0`)

https://github.com/shadowwalker/next-pwa/blob/1e8482c46f9dae12e7f10f01bc12a1614d359990/examples/lifecycle/pages/index.js#L27-L49

**Comment by jingz** [comment]
Thank you for supporting this.
eventually, I upgraded to `3.1.0` getting full control of caching homepage everything seems working.
Since there are existing `runtimeConfig` this will be broken by `start-url` must be in the first item when start server.
Should this be documented ?

**Comment by shadowwalker** [comment]
Will document this
