### ISSUE TITLE
Canary 9.4.5-canary.36 => 9.4.5-canary.37 - can't resolve main.js

### ISSUE THREAD

**Issue by followbl** [shadowwalker/next-pwa#84]
# Summary

Hello 😸 - thank you for next-pwa - it's working great in production for our team.

Opened an issue in the next.js repo and figured you'd want to be alerted on it.

https://github.com/vercel/next.js/issues/15261

Steps to reproduce after cloning https://github.com/followbl/pwa-bug

1. run `yarn run build`

result

`ModuleNotFoundError: Module not found: Error: Can't resolve 'main.js' in`

expected result - no error on build

**Comment by shadowwalker** [comment]
Hi, @followbl thanks for creating the issue. I haven't being monitoring the canary branch. Once there is an official release, I will see what's the breaking changes and how to deal with it.

**Comment by followbl** [comment]
@followbl this has been fix thanks to the nextjs team here - closing the issue https://github.com/vercel/next.js/pull/15311/files

thanks for your support, response and excellent package 😺
