### ISSUE TITLE
Please check your GenerateSW plugin configuration: "startUrl" is not a supported parameter.

### ISSUE THREAD

**Issue by c316** [shadowwalker/next-pwa#87]
# Summary

There is now a build error if you use the, "startUrl".

`Please check your GenerateSW plugin configuration:
"startUrl" is not a supported parameter.`

# How To Reproduce

1. Add `startUrl: '/other-page'` to your next.config.js file
2. set `disabled: true` in the next.config.js file so that it runs on dev
3. run `next dev` to start the next.js dev server

Link to minimal reproduce setup repository if any.

# Expected Behaviors
startUrl is listed in the readme as a valid option, so I'd expect it to work as it did before a recent release

# Screenshots
![image](https://user-images.githubusercontent.com/3142974/88406831-d4f78080-cd96-11ea-8ccc-06b9af574a8b.png)

Also, a workaround for now is to completely remove next-pwa from the package.json, do an `npm install`, then do an `npm install next-pwa@3.0.3` to get the previous release and now it works again.

I think a possible fix might just be to add the startUrl variable back into this line, but I'm not sure.
https://github.com/shadowwalker/next-pwa/blob/1e8482c46f9dae12e7f10f01bc12a1614d359990/index.js#L42

**Comment by shadowwalker** [comment]
In the latest update, I'm giving back full control of `start-url` runtime cache. Please use `runtimeCaching` configuration to change start-url if you need to. Example:

https://github.com/shadowwalker/next-pwa/blob/1e8482c46f9dae12e7f10f01bc12a1614d359990/examples/lifecycle/next.config.js#L5-L6

You will need to do `runtimeCaching[0].urlPattern = '/your-start-url-here'`

**Comment by c316** [comment]
Thank you.
