### ISSUE TITLE
Uncaught (in promise) TypeError: Request method 'POST' is unsupported

### ISSUE THREAD

**Issue by guptamohit004** [shadowwalker/next-pwa#88]
Getting the above error,while signing in or filling up some form.

The submission is successful but not getting to the required page i.e not doing redirect on submission.

**Comment by shadowwalker** [comment]
Can you send full error message? pwa config? Repro steps?

**Comment by guptamohit004** [comment]
PWA Config - [next.config.js](https://raw.githubusercontent.com/guptamohit004/social/master/next.config.js?token=AIBZWKPRA4NPNUZ5KYHH6Y27EVJCS)

Full Error Message -  Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at x (workbox-432e0d0b.js:1) 

Reproduce Error - 
1) Try signing in using at [social](https://socialnext.herokuapp.com) using credentials - username(abcd) , password(abcd).
2) As soon as hit enter signed in and can see the "Error message in console".
3) You are signed in and redirected to homepage.
4) After refreshing comes to profile page.

Behavior before addition of next-pwa.
Signed In and directly redirect to /profile page.

**Comment by shadowwalker** [comment]
After click the sign in button, you set the cookie and routed to `/` path. But it is front end routing, there is no GET request sending out to the server, so your cookie is not validated on the server. If you don't need to validate cookie on server, you can add [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) to your index page, just like your `getServerSideProps`.
