### ISSUE TITLE
Couldn't find configuration for either precaching or runtime caching.

### ISSUE THREAD

**Issue by TrejoCode** [shadowwalker/next-pwa#89]
# Summary

Using **Next.js v9.5** and **next-compose-plugins**
Throw the following error:

```bash
Couldn't find configuration for either precaching or runtime caching. Please ensure that the various glob options are set to match one or more files, and/or configure the runtimeCaching option.
```

# How To Reproduce

1. Edit next.config.js

```js
const withPlugins   = require('next-compose-plugins');
const PWA           = require('next-pwa');
const sass          = require('@zeit/next-sass');

module.exports      = withPlugins([PWA, { pwa: { dest: 'public' } }, sass]);
```

2. See error

**Comment by gauravkrp** [comment]
Yes, having the same issue after I updated to NextJs 9.5 today.

**Comment by minvs1** [comment]
Passing runtime caching manually seems to remove that error however worker seems to glitch and won't register correctly but not sure if this due to my misconfiguration.

```
const runtimeCaching = require('next-pwa/cache')

withPWA({
  pwa: {
    runtimeCaching,
  }
})
```

**Comment by shadowwalker** [comment]
This seems to be the issued caused by `next-compose-plugins`

**Comment by TrejoCode** [comment]
> This seems to be the issued caused by `next-compose-plugins`

Noup, I am no longer using next-compose and the error persists

**Comment by shadowwalker** [comment]
I'm not able to reproduce the errors. The next version 9.5 works fine for my examples. Maybe create a reproduce repository would help.

**Comment by gauravkrp** [comment]
> I'm not able to reproduce the errors. The next version 9.5 works fine for my examples. Maybe create a reproduce repository would help.

Issue disappeared in the later version. I'm using Next.js 10 now.
