### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: [PWA] Fisrt item in runtimeCaching array is not "start-url"

### ISSUE THREAD

**Issue by champseo2017** [shadowwalker/next-pwa#90]
UnhandledPromiseRejectionWarning: Error: [PWA] Fisrt item in runtimeCaching array is not "start-url"

 "dependencies": {
"next": "9.4.4",
"next-pwa": "latest",
}

module.exports = withPlugins([[withPWA,{
  pwa: {
  disable: false, //dev,
  dest: 'public',
  //register: true, // deploy true
  // skipWaiting: true, // deploy true
  runtimeCaching: [
    {
      urlPattern: '/',
      handler: 'NetworkFirst',
      options: {
      cacheName: 'indexpages',
      expiration: {
      maxEntries: 4,
      maxAgeSeconds: 7 * 24 * 60 * 60 // 7 days
      }
      }
      },
    {
    urlPattern: /.(?:eot|otf|ttc|ttf|woff|woff2|font.css)$/i,
    handler: 'NetworkFirst',
    options: {
    cacheName: 'static-font-assets',
    expiration: {
    maxEntries: 4,
    maxAgeSeconds: 7 * 24 * 60 * 60 // 7 days
    }
    }
    },
    {
    urlPattern: /.(?:jpg|jpeg|gif|png|svg|ico|webp)$/i,
    handler: 'NetworkFirst',
    options: {
    cacheName: 'static-image-assets',
    expiration: {
    maxEntries: 64,
    maxAgeSeconds: 24 * 60 * 60 // 24 hours
    }
    }
    },
    {
    urlPattern: /.(?:js)$/i,
    handler: 'NetworkFirst',
    options: {
    cacheName: 'static-js-assets',
    expiration: {
    maxEntries: 16,
    maxAgeSeconds: 24 * 60 * 60 // 24 hours
    }
    }
    },
    {
    urlPattern: /.(?:css|less)$/i,
    handler: 'NetworkFirst',
    options: {
    cacheName: 'static-style-assets',
    expiration: {
    maxEntries: 16,
    maxAgeSeconds: 24 * 60 * 60 // 24 hours
    }
    }
    },
    {
    urlPattern: /.(?:json|xml|csv)$/i,
    handler: 'NetworkFirst',
    options: {
    cacheName: 'static-data-assets',
    expiration: {
    maxEntries: 16,
    maxAgeSeconds: 24 * 60 * 60 // 24 hours
    }
    }
    },
    {
    urlPattern: /.*/i,
    handler: 'NetworkFirst',
    options: {
    cacheName: 'others',
    expiration: {
    maxEntries: 16,
    maxAgeSeconds: 24 * 60 * 60 // 24 hours
    }
    }
    }
    ]
  }
  }]],nextConfig);

**Comment by champseo2017** [comment]
It works in version "next-pwa": "3.0.0",

**Comment by shadowwalker** [comment]
You just need to update the cacheName in
``` javascript
{
urlPattern: '/',
handler: 'NetworkFirst',
options: {
cacheName: 'start-url',  // CHANGE THIS TO start-url
expiration: {
maxEntries: 4,
maxAgeSeconds: 7 * 24 * 60 * 60 // 7 days
}
```

**Comment by champseo2017** [comment]
It works great Thank you so much
{
urlPattern: '/',
handler: 'NetworkFirst',
options: {
cacheName: 'start-url',  // CHANGE THIS TO start-url
expiration: {
maxEntries: 4,
maxAgeSeconds: 7 * 24 * 60 * 60 // 7 days
}
