### ISSUE TITLE
How to use workbox plugins in next.config.js

### ISSUE THREAD

**Issue by hmak-me** [shadowwalker/next-pwa#93]
As the service-worker.js file is generated automatically, we need to make use of plugins from the configuration file. 
For example in my case, I want to serve audio files from my service worker which needs to support Range request header. 

Workbox has a plugin for that purpose: [workbox-range-requests](https://developers.google.com/web/tools/workbox/modules/workbox-range-requests). 

I've tried loading **workbox-range-requests** plugin into the next.config.js and use it in the plugins array of runtimeCaching entries. But as long as this is not a Common JS module, build process will fail all the time. 

So, is there a way that we can use workbox plugins?

**Comment by shadowwalker** [comment]
Unfortunately, this feature is not available from the configuration.
You will need to use inject manifest module, check out this example for some inspiration:
https://github.com/shadowwalker/next-pwa/tree/master/examples/offline-fallback

**Comment by bcjohnblue** [comment]
@hmak-me I find my video can't play on safari, and the reason seems relative to the Range request header too. If you have found a solution, could you give me some advices? Thanks advanced.
