### ISSUE TITLE
Does not register a service worker that controls page and start_url

### ISSUE THREAD

**Issue by thathurtabit** [shadowwalker/next-pwa#94]
# Summary

Hi, firstly thanks for writing this plugin. 👍 

When running my next app (with next-pwa) through Chrome's Lighthouse tool, it states (under PWA test): 

- "Does not register a service worker that controls page and start_url"
- "Current page does not respond with a 200 when offline"
- "start_url does not respond with a 200 when offline (Timed out)"

Interestingly, my Lighthouse Performance score has improved with next-pwa, meaning the SW does seem to be correctly cacheing and supplying the assets?

# How To Reproduce

1. In Chrome (incognito) Go to https://fretmap.app/
2. Click on Dev Tools > Lighthouse
3. Run Test
4. See errors in PWA tab

Link to minimal reproduce setup repository if any.

I can provide a link to my repo if require (it's currently private).

# Expected Behaviors
Should pass PWA tests in Lighthouse

# Additional Context

**Dev setup**

- "next": "^9.5.1",
- "next-pwa": "^3.1.1",
- Uses `/public` folder for static assests (next-pwa correctly places `sw.js` and `workbox*.js` there on `next build`)

**Also,** I'm using a custom `Express` server

**manifest.json**
```
{
...
"start_url": "/",
...
}
```

**next.config.js**
```const withPWA = require('next-pwa');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
    enabled: process.env.ANALYZE === 'true',
});
const runtimeCaching = require('next-pwa/cache');

module.exports = withBundleAnalyzer(
    withPWA({
        pwa: {
            runtimeCaching,
            dest: 'public',
        },
    }),
);
```

**Comment by shadowwalker** [comment]
Seems there is a precache file missing from your server:

```
workbox-432e0d0b.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://fretmap.app/robots.txt","status":404}]
    at P (https://fretmap.app/workbox-432e0d0b.js:1:11330)
    at async Promise.all (index 0)
    at async P.install (https://fretmap.app/workbox-432e0d0b.js:1:10749)
```

You can add the following to your pwa config to prevent this file to be precached

```
publicExcludes: ['!robots.txt']
```

**Comment by thathurtabit** [comment]
@shadowwalker Thank you! I added the following to my config and it works now. It makes sense not to cache the below anyway.

````
withPWA({
        pwa: {
            dest: 'public',
            publicExcludes: [
                '!robots.txt',
                '!sitemap.xml.gz',
            ],
        },
    }),
