### ISSUE TITLE
A fix for errored offline refreshes

### ISSUE THREAD

**Issue by bahumbert** [shadowwalker/next-pwa#95]
Hello, I ran into this issue when using next-pwa which really bothered me. Apparently I'm not the only one since I saw these:
https://github.com/shadowwalker/next-pwa/issues/57 https://github.com/shadowwalker/next-pwa/issues/29

If I can summary this issue quickly here again: since NextJS has frontend AND backend routing, from the browser point of view accessing a page through SSR or "SPA" isn't the same thing at all, when most of the time it's the same content. So as a user, when I have accessed a page through the frontend routing while online, if I try to refresh the page while offline I'd get an error since I'm calling the SSR page, which isn't registered by the Service Worker.

I'd prefer if errors like that could be handled by the JS app and not the browser since it's not that nice for user experience. What do you think?

After a lot of researches I finally found some solutions, I'm creating this issue so we can talk about it. I think it would be a nice addition to this lib, maybe as an activable option, or at least I guess it should be present in your "tips" section, since many people struggle with this apparently. Not sure what do you prefer here.
I'm willing to create a pull request to add this in the lib's inner works, but I'm not sure how to implement this for now, so you'll have to decide what to do first and then maybe guide me a bit 👍 

The solutions are quite simple actually: on each navigation change, use `.fetchAndCache(url)` in the service worker from a runtime cache ; and create a route catch handler so it can send a little html file instead of just nothing.

Here are concrete and quick code examples to add to service-worker.js:
Force cache current page on each route change, so SSR call (refresh) works while offline:
```js
const customCache = new workbox.runtimeCaching.RequestWrapper({
  cacheName: "cache"     // runtime cache name, previously created with a strategy
});
self.addEventListener("message", e => {
  if (e.data && e.data.action === "NAVIGATION") {
    customCache.fetchAndCache({ request: new Request(e.source.url) });
  }
});
```
(Of course for this to work the JS app have to send this "navigation" event to the SW on each route change, nothing fancy here).

Send a fallback html file (which is in the precache-manifest) instead of just nothing when there's a network error:
```js
workbox.routing.setCatchHandler(({event}) => {
  switch (event.request.destination) {
    case 'document':
      return workbox.precaching.matchPrecache('/static/offline.html');
    default: 
      return Response.error()
  }
})
```
This html can explain what's happening and provide a link to come back to the root url of the app, that's what adds the most in user experience terms I think, but it will anyway be at the developers preference.
Sadly we cannot send a .js file here, so if we want the SPA to take over anyway (since it should be accessible through the precache-manifest) this html file has to import the app manually (it's doable I guess, should we do it?).

So what's your call on this? 😄

**Comment by bahumbert** [comment]
Yup, the unsolved case left could only be done with the route catch handler we spoke earlier, the example is enough I think. I'd just add a little sentence in the Tips section, is that okay for you?

I completely agree with you, this behavior should be an activable option since it's quite a niche case.
I'm not sure how to wrap `next/link` though, I thought of something simpler, the developers should implement the event sender in their apps by themselves.
We could provide an example to do that along with the option's explanation:
```js
// Somewhere in the app, e.g.: _app.js
  useEffect(() => {
    notifySwOnRouteChange()
  }, [isOnline, router.asPath])

  const notifySwOnRouteChange = async () => {
    if (isOnline) {   // An internal state that monitors if your app is online or not, to prevent unnecessary API calls
      await navigator.serviceWorker.ready
      navigator.serviceWorker.controller.postMessage({ action: "NAVIGATION" })
    }
  };
```

But yeah maybe it'd be preferable if everything was done directly by next-pwa, so how do I do that? 😅

**Comment by prabu-ssb** [comment]
@bahumbert : could you share your next.config.js, and service-worker.js files ? Does your solution require a custom server ?

**Comment by bahumbert** [comment]
@prabu-ssb Well I stopped using next-pwa when facing those issues, I created this thread precisely to be able to use next-pwa with those fixes. I don't think it's currently possible to add those without modifying next-pwa internals, but I'm not sure about that I may be wrong here. @shadowwalker will know for sure I guess 😄

**Comment by prabu-ssb** [comment]
@bahumbert : may I ask how you got around to implement it ? We fall in the niche you are referring to :)

**Comment by shadowwalker** [comment]
@bahumbert and @prabu-ssb I added an example for this issue, this should help you work out the case:

https://github.com/shadowwalker/next-pwa/tree/master/examples/cache-on-front-end-nav

**Comment by prabu-ssb** [comment]
@shadowwalker : thanks! Will try this today and get back!

**Comment by bahumbert** [comment]
Well that's perfect thanks!

**Comment by cvolant** [comment]
Hi,
Sorry to revive this issue from the closed, I just thought of something about it.
But first, thank you to both of you, for this great plugin and for documenting this issue so well.

For the context, I work on a website with a lot of dynamic pages : the trade-off of the solution you suggest is too high. But I thought of a middle-ground solution that might work: what about intercepting requests to html pages, and serve any of them with the precached startUrl page (maybe using a redirection)? That would avoid a broken site offline and too much extra requests/caching. We could then even think about a way of automatically perform a client-side router.redirect.
What do you think?
